# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import common_pb2 as base_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\nchat.proto\x1a\x11\x62\x61se/common.proto\"\x88\x01\n\x08RoleInfo\x12\x0b\n\x03pid\x18\x01 \x01(\r\x12\r\n\x05grade\x18\x02 \x01(\r\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04icon\x18\x04 \x01(\r\x12\x10\n\x08position\x18\x05 \x01(\r\x12\r\n\x05honor\x18\x06 \x01(\r\x12#\n\ntitle_info\x18\x07 \x01(\x0b\x32\x0f.base.TitleInfo\"C\n\x08GS2CChat\x12\x0b\n\x03\x63md\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\r\x12\x1c\n\trole_info\x18\x03 \x01(\x0b\x32\t.RoleInfo\"k\n\x0fGS2CChatHistory\x12\x1d\n\nworld_chat\x18\x01 \x03(\x0b\x32\t.GS2CChat\x12\x1b\n\x08org_chat\x18\x02 \x03(\x0b\x32\t.GS2CChat\x12\x1c\n\tteam_chat\x18\x03 \x03(\x0b\x32\t.GS2CChat\"D\n\x0bGS2CSysChat\x12\x10\n\x08tag_type\x18\x01 \x01(\r\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x12\n\nhorse_race\x18\x03 \x01(\r\"/\n\x0eGS2CConsumeMsg\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"G\n\x0cGS2CChuanYin\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\x0b\n\x03\x63md\x18\x02 \x01(\t\x12\x1c\n\trole_info\x18\x03 \x01(\x0b\x32\t.RoleInfo\"\'\n\nForbidInfo\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05words\x18\x02 \x01(\t\"1\n\x11GS2CAllForbinInfo\x12\x1c\n\x07\x66orbids\x18\x01 \x03(\x0b\x32\x0b.ForbidInfo\"1\n\x11GS2CAddForbinInfo\x12\x1c\n\x07\x66orbids\x18\x01 \x03(\x0b\x32\x0b.ForbidInfo\"\'\n\x14GS2CRemoveForbinInfo\x12\x0f\n\x07\x66orbids\x18\x01 \x03(\r')
  ,
  dependencies=[base_dot_common__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ROLEINFO = _descriptor.Descriptor(
  name='RoleInfo',
  full_name='RoleInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='RoleInfo.pid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='grade', full_name='RoleInfo.grade', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='RoleInfo.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='icon', full_name='RoleInfo.icon', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='RoleInfo.position', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='honor', full_name='RoleInfo.honor', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='title_info', full_name='RoleInfo.title_info', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=170,
)


_GS2CCHAT = _descriptor.Descriptor(
  name='GS2CChat',
  full_name='GS2CChat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='GS2CChat.cmd', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='GS2CChat.type', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='role_info', full_name='GS2CChat.role_info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=239,
)


_GS2CCHATHISTORY = _descriptor.Descriptor(
  name='GS2CChatHistory',
  full_name='GS2CChatHistory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='world_chat', full_name='GS2CChatHistory.world_chat', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='org_chat', full_name='GS2CChatHistory.org_chat', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='team_chat', full_name='GS2CChatHistory.team_chat', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=348,
)


_GS2CSYSCHAT = _descriptor.Descriptor(
  name='GS2CSysChat',
  full_name='GS2CSysChat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag_type', full_name='GS2CSysChat.tag_type', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='GS2CSysChat.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='horse_race', full_name='GS2CSysChat.horse_race', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=350,
  serialized_end=418,
)


_GS2CCONSUMEMSG = _descriptor.Descriptor(
  name='GS2CConsumeMsg',
  full_name='GS2CConsumeMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='GS2CConsumeMsg.type', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='GS2CConsumeMsg.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=420,
  serialized_end=467,
)


_GS2CCHUANYIN = _descriptor.Descriptor(
  name='GS2CChuanYin',
  full_name='GS2CChuanYin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='GS2CChuanYin.type', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cmd', full_name='GS2CChuanYin.cmd', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='role_info', full_name='GS2CChuanYin.role_info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=469,
  serialized_end=540,
)


_FORBIDINFO = _descriptor.Descriptor(
  name='ForbidInfo',
  full_name='ForbidInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ForbidInfo.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='words', full_name='ForbidInfo.words', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=542,
  serialized_end=581,
)


_GS2CALLFORBININFO = _descriptor.Descriptor(
  name='GS2CAllForbinInfo',
  full_name='GS2CAllForbinInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='forbids', full_name='GS2CAllForbinInfo.forbids', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=583,
  serialized_end=632,
)


_GS2CADDFORBININFO = _descriptor.Descriptor(
  name='GS2CAddForbinInfo',
  full_name='GS2CAddForbinInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='forbids', full_name='GS2CAddForbinInfo.forbids', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=634,
  serialized_end=683,
)


_GS2CREMOVEFORBININFO = _descriptor.Descriptor(
  name='GS2CRemoveForbinInfo',
  full_name='GS2CRemoveForbinInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='forbids', full_name='GS2CRemoveForbinInfo.forbids', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=685,
  serialized_end=724,
)

_ROLEINFO.fields_by_name['title_info'].message_type = base_dot_common__pb2._TITLEINFO
_GS2CCHAT.fields_by_name['role_info'].message_type = _ROLEINFO
_GS2CCHATHISTORY.fields_by_name['world_chat'].message_type = _GS2CCHAT
_GS2CCHATHISTORY.fields_by_name['org_chat'].message_type = _GS2CCHAT
_GS2CCHATHISTORY.fields_by_name['team_chat'].message_type = _GS2CCHAT
_GS2CCHUANYIN.fields_by_name['role_info'].message_type = _ROLEINFO
_GS2CALLFORBININFO.fields_by_name['forbids'].message_type = _FORBIDINFO
_GS2CADDFORBININFO.fields_by_name['forbids'].message_type = _FORBIDINFO
DESCRIPTOR.message_types_by_name['RoleInfo'] = _ROLEINFO
DESCRIPTOR.message_types_by_name['GS2CChat'] = _GS2CCHAT
DESCRIPTOR.message_types_by_name['GS2CChatHistory'] = _GS2CCHATHISTORY
DESCRIPTOR.message_types_by_name['GS2CSysChat'] = _GS2CSYSCHAT
DESCRIPTOR.message_types_by_name['GS2CConsumeMsg'] = _GS2CCONSUMEMSG
DESCRIPTOR.message_types_by_name['GS2CChuanYin'] = _GS2CCHUANYIN
DESCRIPTOR.message_types_by_name['ForbidInfo'] = _FORBIDINFO
DESCRIPTOR.message_types_by_name['GS2CAllForbinInfo'] = _GS2CALLFORBININFO
DESCRIPTOR.message_types_by_name['GS2CAddForbinInfo'] = _GS2CADDFORBININFO
DESCRIPTOR.message_types_by_name['GS2CRemoveForbinInfo'] = _GS2CREMOVEFORBININFO

RoleInfo = _reflection.GeneratedProtocolMessageType('RoleInfo', (_message.Message,), dict(
  DESCRIPTOR = _ROLEINFO,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:RoleInfo)
  ))
_sym_db.RegisterMessage(RoleInfo)

GS2CChat = _reflection.GeneratedProtocolMessageType('GS2CChat', (_message.Message,), dict(
  DESCRIPTOR = _GS2CCHAT,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:GS2CChat)
  ))
_sym_db.RegisterMessage(GS2CChat)

GS2CChatHistory = _reflection.GeneratedProtocolMessageType('GS2CChatHistory', (_message.Message,), dict(
  DESCRIPTOR = _GS2CCHATHISTORY,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:GS2CChatHistory)
  ))
_sym_db.RegisterMessage(GS2CChatHistory)

GS2CSysChat = _reflection.GeneratedProtocolMessageType('GS2CSysChat', (_message.Message,), dict(
  DESCRIPTOR = _GS2CSYSCHAT,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:GS2CSysChat)
  ))
_sym_db.RegisterMessage(GS2CSysChat)

GS2CConsumeMsg = _reflection.GeneratedProtocolMessageType('GS2CConsumeMsg', (_message.Message,), dict(
  DESCRIPTOR = _GS2CCONSUMEMSG,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:GS2CConsumeMsg)
  ))
_sym_db.RegisterMessage(GS2CConsumeMsg)

GS2CChuanYin = _reflection.GeneratedProtocolMessageType('GS2CChuanYin', (_message.Message,), dict(
  DESCRIPTOR = _GS2CCHUANYIN,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:GS2CChuanYin)
  ))
_sym_db.RegisterMessage(GS2CChuanYin)

ForbidInfo = _reflection.GeneratedProtocolMessageType('ForbidInfo', (_message.Message,), dict(
  DESCRIPTOR = _FORBIDINFO,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:ForbidInfo)
  ))
_sym_db.RegisterMessage(ForbidInfo)

GS2CAllForbinInfo = _reflection.GeneratedProtocolMessageType('GS2CAllForbinInfo', (_message.Message,), dict(
  DESCRIPTOR = _GS2CALLFORBININFO,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:GS2CAllForbinInfo)
  ))
_sym_db.RegisterMessage(GS2CAllForbinInfo)

GS2CAddForbinInfo = _reflection.GeneratedProtocolMessageType('GS2CAddForbinInfo', (_message.Message,), dict(
  DESCRIPTOR = _GS2CADDFORBININFO,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:GS2CAddForbinInfo)
  ))
_sym_db.RegisterMessage(GS2CAddForbinInfo)

GS2CRemoveForbinInfo = _reflection.GeneratedProtocolMessageType('GS2CRemoveForbinInfo', (_message.Message,), dict(
  DESCRIPTOR = _GS2CREMOVEFORBININFO,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:GS2CRemoveForbinInfo)
  ))
_sym_db.RegisterMessage(GS2CRemoveForbinInfo)


# @@protoc_insertion_point(module_scope)
