# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: engage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='engage.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0c\x65ngage.proto\"c\n\nMemberInfo\x12\x0b\n\x03pid\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03sex\x18\x03 \x01(\r\x12\r\n\x05grade\x18\x04 \x01(\r\x12\x0e\n\x06\x64\x65gree\x18\x05 \x01(\r\x12\x0e\n\x06\x63ouple\x18\x06 \x01(\r\"Q\n\x13GS2CEngageCondition\x12\x1c\n\x07members\x18\x01 \x03(\x0b\x32\x0b.MemberInfo\x12\x0c\n\x04type\x18\x02 \x01(\r\x12\x0e\n\x06status\x18\x03 \x01(\r\"\x17\n\x15GS2CStartEngageResult\"\x12\n\x10GS2CCancelEngage\"\x15\n\x13GS2CSetEngageTextUI\"\x19\n\x17GS2CSetEngageTextRusult\"!\n\x11GS2CEngageSuccess\x12\x0c\n\x04type\x18\x01 \x01(\r\"!\n\x11GS2CEngageOperate\x12\x0c\n\x04type\x18\x01 \x01(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MEMBERINFO = _descriptor.Descriptor(
  name='MemberInfo',
  full_name='MemberInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='MemberInfo.pid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='MemberInfo.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sex', full_name='MemberInfo.sex', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='grade', full_name='MemberInfo.grade', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='degree', full_name='MemberInfo.degree', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='couple', full_name='MemberInfo.couple', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=115,
)


_GS2CENGAGECONDITION = _descriptor.Descriptor(
  name='GS2CEngageCondition',
  full_name='GS2CEngageCondition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='members', full_name='GS2CEngageCondition.members', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='GS2CEngageCondition.type', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='GS2CEngageCondition.status', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=198,
)


_GS2CSTARTENGAGERESULT = _descriptor.Descriptor(
  name='GS2CStartEngageResult',
  full_name='GS2CStartEngageResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=223,
)


_GS2CCANCELENGAGE = _descriptor.Descriptor(
  name='GS2CCancelEngage',
  full_name='GS2CCancelEngage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=243,
)


_GS2CSETENGAGETEXTUI = _descriptor.Descriptor(
  name='GS2CSetEngageTextUI',
  full_name='GS2CSetEngageTextUI',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=266,
)


_GS2CSETENGAGETEXTRUSULT = _descriptor.Descriptor(
  name='GS2CSetEngageTextRusult',
  full_name='GS2CSetEngageTextRusult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=293,
)


_GS2CENGAGESUCCESS = _descriptor.Descriptor(
  name='GS2CEngageSuccess',
  full_name='GS2CEngageSuccess',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='GS2CEngageSuccess.type', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=295,
  serialized_end=328,
)


_GS2CENGAGEOPERATE = _descriptor.Descriptor(
  name='GS2CEngageOperate',
  full_name='GS2CEngageOperate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='GS2CEngageOperate.type', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=330,
  serialized_end=363,
)

_GS2CENGAGECONDITION.fields_by_name['members'].message_type = _MEMBERINFO
DESCRIPTOR.message_types_by_name['MemberInfo'] = _MEMBERINFO
DESCRIPTOR.message_types_by_name['GS2CEngageCondition'] = _GS2CENGAGECONDITION
DESCRIPTOR.message_types_by_name['GS2CStartEngageResult'] = _GS2CSTARTENGAGERESULT
DESCRIPTOR.message_types_by_name['GS2CCancelEngage'] = _GS2CCANCELENGAGE
DESCRIPTOR.message_types_by_name['GS2CSetEngageTextUI'] = _GS2CSETENGAGETEXTUI
DESCRIPTOR.message_types_by_name['GS2CSetEngageTextRusult'] = _GS2CSETENGAGETEXTRUSULT
DESCRIPTOR.message_types_by_name['GS2CEngageSuccess'] = _GS2CENGAGESUCCESS
DESCRIPTOR.message_types_by_name['GS2CEngageOperate'] = _GS2CENGAGEOPERATE

MemberInfo = _reflection.GeneratedProtocolMessageType('MemberInfo', (_message.Message,), dict(
  DESCRIPTOR = _MEMBERINFO,
  __module__ = 'engage_pb2'
  # @@protoc_insertion_point(class_scope:MemberInfo)
  ))
_sym_db.RegisterMessage(MemberInfo)

GS2CEngageCondition = _reflection.GeneratedProtocolMessageType('GS2CEngageCondition', (_message.Message,), dict(
  DESCRIPTOR = _GS2CENGAGECONDITION,
  __module__ = 'engage_pb2'
  # @@protoc_insertion_point(class_scope:GS2CEngageCondition)
  ))
_sym_db.RegisterMessage(GS2CEngageCondition)

GS2CStartEngageResult = _reflection.GeneratedProtocolMessageType('GS2CStartEngageResult', (_message.Message,), dict(
  DESCRIPTOR = _GS2CSTARTENGAGERESULT,
  __module__ = 'engage_pb2'
  # @@protoc_insertion_point(class_scope:GS2CStartEngageResult)
  ))
_sym_db.RegisterMessage(GS2CStartEngageResult)

GS2CCancelEngage = _reflection.GeneratedProtocolMessageType('GS2CCancelEngage', (_message.Message,), dict(
  DESCRIPTOR = _GS2CCANCELENGAGE,
  __module__ = 'engage_pb2'
  # @@protoc_insertion_point(class_scope:GS2CCancelEngage)
  ))
_sym_db.RegisterMessage(GS2CCancelEngage)

GS2CSetEngageTextUI = _reflection.GeneratedProtocolMessageType('GS2CSetEngageTextUI', (_message.Message,), dict(
  DESCRIPTOR = _GS2CSETENGAGETEXTUI,
  __module__ = 'engage_pb2'
  # @@protoc_insertion_point(class_scope:GS2CSetEngageTextUI)
  ))
_sym_db.RegisterMessage(GS2CSetEngageTextUI)

GS2CSetEngageTextRusult = _reflection.GeneratedProtocolMessageType('GS2CSetEngageTextRusult', (_message.Message,), dict(
  DESCRIPTOR = _GS2CSETENGAGETEXTRUSULT,
  __module__ = 'engage_pb2'
  # @@protoc_insertion_point(class_scope:GS2CSetEngageTextRusult)
  ))
_sym_db.RegisterMessage(GS2CSetEngageTextRusult)

GS2CEngageSuccess = _reflection.GeneratedProtocolMessageType('GS2CEngageSuccess', (_message.Message,), dict(
  DESCRIPTOR = _GS2CENGAGESUCCESS,
  __module__ = 'engage_pb2'
  # @@protoc_insertion_point(class_scope:GS2CEngageSuccess)
  ))
_sym_db.RegisterMessage(GS2CEngageSuccess)

GS2CEngageOperate = _reflection.GeneratedProtocolMessageType('GS2CEngageOperate', (_message.Message,), dict(
  DESCRIPTOR = _GS2CENGAGEOPERATE,
  __module__ = 'engage_pb2'
  # @@protoc_insertion_point(class_scope:GS2CEngageOperate)
  ))
_sym_db.RegisterMessage(GS2CEngageOperate)


# @@protoc_insertion_point(module_scope)
