# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: formation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='formation.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0f\x66ormation.proto\"5\n\x07\x46mtUnit\x12\x0e\n\x06\x66mt_id\x18\x01 \x01(\r\x12\x0b\n\x03\x65xp\x18\x02 \x01(\r\x12\r\n\x05grade\x18\x03 \x01(\r\"\x88\x01\n\x14GS2CAllFormationInfo\x12\x10\n\x08\x66mt_curr\x18\x01 \x01(\r\x12\x13\n\x0bplayer_list\x18\x02 \x03(\r\x12\x14\n\x0cpartner_list\x18\x03 \x03(\r\x12\x1a\n\x08\x66mt_list\x18\x04 \x03(\x0b\x32\x08.FmtUnit\x12\x17\n\x0f\x66mt_learn_limit\x18\x05 \x01(\r\"N\n\x17GS2CSingleFormationInfo\x12\x1a\n\x08\x66mt_info\x18\x01 \x01(\x0b\x32\x08.FmtUnit\x12\x17\n\x0f\x66mt_learn_limit\x18\x02 \x01(\r\"M\n\x0eGS2CFmtPosInfo\x12\x10\n\x08\x66mt_curr\x18\x01 \x01(\r\x12\x13\n\x0bplayer_list\x18\x02 \x03(\r\x12\x14\n\x0cpartner_list\x18\x03 \x03(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FMTUNIT = _descriptor.Descriptor(
  name='FmtUnit',
  full_name='FmtUnit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fmt_id', full_name='FmtUnit.fmt_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exp', full_name='FmtUnit.exp', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='grade', full_name='FmtUnit.grade', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=72,
)


_GS2CALLFORMATIONINFO = _descriptor.Descriptor(
  name='GS2CAllFormationInfo',
  full_name='GS2CAllFormationInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fmt_curr', full_name='GS2CAllFormationInfo.fmt_curr', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_list', full_name='GS2CAllFormationInfo.player_list', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='partner_list', full_name='GS2CAllFormationInfo.partner_list', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fmt_list', full_name='GS2CAllFormationInfo.fmt_list', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fmt_learn_limit', full_name='GS2CAllFormationInfo.fmt_learn_limit', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=211,
)


_GS2CSINGLEFORMATIONINFO = _descriptor.Descriptor(
  name='GS2CSingleFormationInfo',
  full_name='GS2CSingleFormationInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fmt_info', full_name='GS2CSingleFormationInfo.fmt_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fmt_learn_limit', full_name='GS2CSingleFormationInfo.fmt_learn_limit', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=291,
)


_GS2CFMTPOSINFO = _descriptor.Descriptor(
  name='GS2CFmtPosInfo',
  full_name='GS2CFmtPosInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fmt_curr', full_name='GS2CFmtPosInfo.fmt_curr', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_list', full_name='GS2CFmtPosInfo.player_list', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='partner_list', full_name='GS2CFmtPosInfo.partner_list', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=370,
)

_GS2CALLFORMATIONINFO.fields_by_name['fmt_list'].message_type = _FMTUNIT
_GS2CSINGLEFORMATIONINFO.fields_by_name['fmt_info'].message_type = _FMTUNIT
DESCRIPTOR.message_types_by_name['FmtUnit'] = _FMTUNIT
DESCRIPTOR.message_types_by_name['GS2CAllFormationInfo'] = _GS2CALLFORMATIONINFO
DESCRIPTOR.message_types_by_name['GS2CSingleFormationInfo'] = _GS2CSINGLEFORMATIONINFO
DESCRIPTOR.message_types_by_name['GS2CFmtPosInfo'] = _GS2CFMTPOSINFO

FmtUnit = _reflection.GeneratedProtocolMessageType('FmtUnit', (_message.Message,), dict(
  DESCRIPTOR = _FMTUNIT,
  __module__ = 'formation_pb2'
  # @@protoc_insertion_point(class_scope:FmtUnit)
  ))
_sym_db.RegisterMessage(FmtUnit)

GS2CAllFormationInfo = _reflection.GeneratedProtocolMessageType('GS2CAllFormationInfo', (_message.Message,), dict(
  DESCRIPTOR = _GS2CALLFORMATIONINFO,
  __module__ = 'formation_pb2'
  # @@protoc_insertion_point(class_scope:GS2CAllFormationInfo)
  ))
_sym_db.RegisterMessage(GS2CAllFormationInfo)

GS2CSingleFormationInfo = _reflection.GeneratedProtocolMessageType('GS2CSingleFormationInfo', (_message.Message,), dict(
  DESCRIPTOR = _GS2CSINGLEFORMATIONINFO,
  __module__ = 'formation_pb2'
  # @@protoc_insertion_point(class_scope:GS2CSingleFormationInfo)
  ))
_sym_db.RegisterMessage(GS2CSingleFormationInfo)

GS2CFmtPosInfo = _reflection.GeneratedProtocolMessageType('GS2CFmtPosInfo', (_message.Message,), dict(
  DESCRIPTOR = _GS2CFMTPOSINFO,
  __module__ = 'formation_pb2'
  # @@protoc_insertion_point(class_scope:GS2CFmtPosInfo)
  ))
_sym_db.RegisterMessage(GS2CFmtPosInfo)


# @@protoc_insertion_point(module_scope)
