# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mail.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import common_pb2 as base_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mail.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\nmail.proto\x1a\x11\x62\x61se/common.proto\"\xcd\x01\n\x0eMailSimpleInfo\x12\x0e\n\x06mailid\x18\x01 \x01(\r\x12\r\n\x05title\x18\x02 \x01(\t\x12\x11\n\tvalidtime\x18\x03 \x01(\r\x12\x11\n\thasattach\x18\x04 \x01(\r\x12\x0e\n\x06opened\x18\x05 \x01(\r\x12\x11\n\treadtodel\x18\x06 \x01(\r\x12\x12\n\ncreatetime\x18\x07 \x01(\r\x12\x10\n\x08mailtype\x18\x08 \x01(\r\x12\x0c\n\x04icon\x18\t \x01(\t\x12\x10\n\x08openicon\x18\n \x01(\t\x12\r\n\x05\x61udio\x18\x0b \x01(\t\"4\n\rGS2CLoginMail\x12#\n\nsimpleinfo\x18\x01 \x03(\x0b\x32\x0f.MailSimpleInfo\"4\n\nAttachInfo\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\x0b\n\x03sid\x18\x02 \x01(\r\x12\x0b\n\x03val\x18\x03 \x01(\r\"\xc1\x01\n\x0cGS2CMailInfo\x12\x0e\n\x06mailid\x18\x01 \x01(\r\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x03 \x01(\t\x12\x12\n\ncreatetime\x18\x04 \x01(\r\x12\x11\n\tvalidtime\x18\x05 \x01(\r\x12\x0b\n\x03pid\x18\x06 \x01(\r\x12\x0c\n\x04name\x18\x07 \x01(\t\x12\x0e\n\x06opened\x18\x08 \x01(\r\x12\x11\n\thasattach\x18\t \x01(\r\x12\x1c\n\x07\x61ttachs\x18\n \x03(\x0b\x32\x0b.AttachInfo\"\x1e\n\x0bGS2CDelMail\x12\x0f\n\x07mailids\x18\x01 \x03(\r\"2\n\x0bGS2CAddMail\x12#\n\nsimpleinfo\x18\x01 \x01(\x0b\x32\x0f.MailSimpleInfo\"!\n\x0eGS2CMailOpened\x12\x0f\n\x07mailids\x18\x01 \x03(\r')
  ,
  dependencies=[base_dot_common__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MAILSIMPLEINFO = _descriptor.Descriptor(
  name='MailSimpleInfo',
  full_name='MailSimpleInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mailid', full_name='MailSimpleInfo.mailid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='title', full_name='MailSimpleInfo.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='validtime', full_name='MailSimpleInfo.validtime', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hasattach', full_name='MailSimpleInfo.hasattach', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='opened', full_name='MailSimpleInfo.opened', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='readtodel', full_name='MailSimpleInfo.readtodel', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='createtime', full_name='MailSimpleInfo.createtime', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mailtype', full_name='MailSimpleInfo.mailtype', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='icon', full_name='MailSimpleInfo.icon', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='openicon', full_name='MailSimpleInfo.openicon', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='audio', full_name='MailSimpleInfo.audio', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=239,
)


_GS2CLOGINMAIL = _descriptor.Descriptor(
  name='GS2CLoginMail',
  full_name='GS2CLoginMail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='simpleinfo', full_name='GS2CLoginMail.simpleinfo', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=293,
)


_ATTACHINFO = _descriptor.Descriptor(
  name='AttachInfo',
  full_name='AttachInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='AttachInfo.type', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sid', full_name='AttachInfo.sid', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='val', full_name='AttachInfo.val', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=295,
  serialized_end=347,
)


_GS2CMAILINFO = _descriptor.Descriptor(
  name='GS2CMailInfo',
  full_name='GS2CMailInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mailid', full_name='GS2CMailInfo.mailid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='title', full_name='GS2CMailInfo.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='context', full_name='GS2CMailInfo.context', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='createtime', full_name='GS2CMailInfo.createtime', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='validtime', full_name='GS2CMailInfo.validtime', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pid', full_name='GS2CMailInfo.pid', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='GS2CMailInfo.name', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='opened', full_name='GS2CMailInfo.opened', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hasattach', full_name='GS2CMailInfo.hasattach', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attachs', full_name='GS2CMailInfo.attachs', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=350,
  serialized_end=543,
)


_GS2CDELMAIL = _descriptor.Descriptor(
  name='GS2CDelMail',
  full_name='GS2CDelMail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mailids', full_name='GS2CDelMail.mailids', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=545,
  serialized_end=575,
)


_GS2CADDMAIL = _descriptor.Descriptor(
  name='GS2CAddMail',
  full_name='GS2CAddMail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='simpleinfo', full_name='GS2CAddMail.simpleinfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=577,
  serialized_end=627,
)


_GS2CMAILOPENED = _descriptor.Descriptor(
  name='GS2CMailOpened',
  full_name='GS2CMailOpened',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mailids', full_name='GS2CMailOpened.mailids', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=629,
  serialized_end=662,
)

_GS2CLOGINMAIL.fields_by_name['simpleinfo'].message_type = _MAILSIMPLEINFO
_GS2CMAILINFO.fields_by_name['attachs'].message_type = _ATTACHINFO
_GS2CADDMAIL.fields_by_name['simpleinfo'].message_type = _MAILSIMPLEINFO
DESCRIPTOR.message_types_by_name['MailSimpleInfo'] = _MAILSIMPLEINFO
DESCRIPTOR.message_types_by_name['GS2CLoginMail'] = _GS2CLOGINMAIL
DESCRIPTOR.message_types_by_name['AttachInfo'] = _ATTACHINFO
DESCRIPTOR.message_types_by_name['GS2CMailInfo'] = _GS2CMAILINFO
DESCRIPTOR.message_types_by_name['GS2CDelMail'] = _GS2CDELMAIL
DESCRIPTOR.message_types_by_name['GS2CAddMail'] = _GS2CADDMAIL
DESCRIPTOR.message_types_by_name['GS2CMailOpened'] = _GS2CMAILOPENED

MailSimpleInfo = _reflection.GeneratedProtocolMessageType('MailSimpleInfo', (_message.Message,), dict(
  DESCRIPTOR = _MAILSIMPLEINFO,
  __module__ = 'mail_pb2'
  # @@protoc_insertion_point(class_scope:MailSimpleInfo)
  ))
_sym_db.RegisterMessage(MailSimpleInfo)

GS2CLoginMail = _reflection.GeneratedProtocolMessageType('GS2CLoginMail', (_message.Message,), dict(
  DESCRIPTOR = _GS2CLOGINMAIL,
  __module__ = 'mail_pb2'
  # @@protoc_insertion_point(class_scope:GS2CLoginMail)
  ))
_sym_db.RegisterMessage(GS2CLoginMail)

AttachInfo = _reflection.GeneratedProtocolMessageType('AttachInfo', (_message.Message,), dict(
  DESCRIPTOR = _ATTACHINFO,
  __module__ = 'mail_pb2'
  # @@protoc_insertion_point(class_scope:AttachInfo)
  ))
_sym_db.RegisterMessage(AttachInfo)

GS2CMailInfo = _reflection.GeneratedProtocolMessageType('GS2CMailInfo', (_message.Message,), dict(
  DESCRIPTOR = _GS2CMAILINFO,
  __module__ = 'mail_pb2'
  # @@protoc_insertion_point(class_scope:GS2CMailInfo)
  ))
_sym_db.RegisterMessage(GS2CMailInfo)

GS2CDelMail = _reflection.GeneratedProtocolMessageType('GS2CDelMail', (_message.Message,), dict(
  DESCRIPTOR = _GS2CDELMAIL,
  __module__ = 'mail_pb2'
  # @@protoc_insertion_point(class_scope:GS2CDelMail)
  ))
_sym_db.RegisterMessage(GS2CDelMail)

GS2CAddMail = _reflection.GeneratedProtocolMessageType('GS2CAddMail', (_message.Message,), dict(
  DESCRIPTOR = _GS2CADDMAIL,
  __module__ = 'mail_pb2'
  # @@protoc_insertion_point(class_scope:GS2CAddMail)
  ))
_sym_db.RegisterMessage(GS2CAddMail)

GS2CMailOpened = _reflection.GeneratedProtocolMessageType('GS2CMailOpened', (_message.Message,), dict(
  DESCRIPTOR = _GS2CMAILOPENED,
  __module__ = 'mail_pb2'
  # @@protoc_insertion_point(class_scope:GS2CMailOpened)
  ))
_sym_db.RegisterMessage(GS2CMailOpened)


# @@protoc_insertion_point(module_scope)
