# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: marry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import common_pb2 as base_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='marry.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0bmarry.proto\x1a\x11\x62\x61se/common.proto\"1\n\x0eGS2CMarryPayUI\x12\x0f\n\x07seconds\x18\x01 \x01(\r\x12\x0e\n\x06status\x18\x02 \x01(\r\"\x11\n\x0fGS2CMarryCancel\"\x14\n\x12GS2CSuccessDivorce\"\x10\n\x0eGS2CPickItemXT\"y\n\x0bMarryPlayer\x12\x0b\n\x03pid\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05grade\x18\x03 \x01(\r\x12\x0e\n\x06school\x18\x04 \x01(\r\x12\x0b\n\x03sex\x18\x05 \x01(\r\x12#\n\nmodel_info\x18\x06 \x01(\x0b\x32\x0f.base.ModelInfo\"\xa1\x01\n\x10GS2CMarryWedding\x12\x10\n\x08marry_no\x18\x01 \x01(\r\x12\x1d\n\x07player1\x18\x02 \x01(\x0b\x32\x0c.MarryPlayer\x12\x1d\n\x07player2\x18\x03 \x01(\x0b\x32\x0c.MarryPlayer\x12\x12\n\nmarry_type\x18\x04 \x01(\r\x12\x14\n\x0cwedding_time\x18\x05 \x01(\r\x12\x13\n\x0bwedding_sec\x18\x06 \x01(\r\"\'\n\x13GS2CMarryWeddingEnd\x12\x10\n\x08marry_no\x18\x01 \x01(\r\"\x15\n\x13GS2CTeamShowWedding\"5\n\x12GS2CMarryConfirmUI\x12\x0f\n\x07seconds\x18\x01 \x01(\r\x12\x0e\n\x06status\x18\x02 \x01(\r')
  ,
  dependencies=[base_dot_common__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GS2CMARRYPAYUI = _descriptor.Descriptor(
  name='GS2CMarryPayUI',
  full_name='GS2CMarryPayUI',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seconds', full_name='GS2CMarryPayUI.seconds', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='GS2CMarryPayUI.status', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=83,
)


_GS2CMARRYCANCEL = _descriptor.Descriptor(
  name='GS2CMarryCancel',
  full_name='GS2CMarryCancel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=102,
)


_GS2CSUCCESSDIVORCE = _descriptor.Descriptor(
  name='GS2CSuccessDivorce',
  full_name='GS2CSuccessDivorce',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=124,
)


_GS2CPICKITEMXT = _descriptor.Descriptor(
  name='GS2CPickItemXT',
  full_name='GS2CPickItemXT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=142,
)


_MARRYPLAYER = _descriptor.Descriptor(
  name='MarryPlayer',
  full_name='MarryPlayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='MarryPlayer.pid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='MarryPlayer.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='grade', full_name='MarryPlayer.grade', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='school', full_name='MarryPlayer.school', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sex', full_name='MarryPlayer.sex', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model_info', full_name='MarryPlayer.model_info', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=265,
)


_GS2CMARRYWEDDING = _descriptor.Descriptor(
  name='GS2CMarryWedding',
  full_name='GS2CMarryWedding',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='marry_no', full_name='GS2CMarryWedding.marry_no', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player1', full_name='GS2CMarryWedding.player1', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player2', full_name='GS2CMarryWedding.player2', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='marry_type', full_name='GS2CMarryWedding.marry_type', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wedding_time', full_name='GS2CMarryWedding.wedding_time', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wedding_sec', full_name='GS2CMarryWedding.wedding_sec', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=429,
)


_GS2CMARRYWEDDINGEND = _descriptor.Descriptor(
  name='GS2CMarryWeddingEnd',
  full_name='GS2CMarryWeddingEnd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='marry_no', full_name='GS2CMarryWeddingEnd.marry_no', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=431,
  serialized_end=470,
)


_GS2CTEAMSHOWWEDDING = _descriptor.Descriptor(
  name='GS2CTeamShowWedding',
  full_name='GS2CTeamShowWedding',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=472,
  serialized_end=493,
)


_GS2CMARRYCONFIRMUI = _descriptor.Descriptor(
  name='GS2CMarryConfirmUI',
  full_name='GS2CMarryConfirmUI',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seconds', full_name='GS2CMarryConfirmUI.seconds', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='GS2CMarryConfirmUI.status', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=495,
  serialized_end=548,
)

_MARRYPLAYER.fields_by_name['model_info'].message_type = base_dot_common__pb2._MODELINFO
_GS2CMARRYWEDDING.fields_by_name['player1'].message_type = _MARRYPLAYER
_GS2CMARRYWEDDING.fields_by_name['player2'].message_type = _MARRYPLAYER
DESCRIPTOR.message_types_by_name['GS2CMarryPayUI'] = _GS2CMARRYPAYUI
DESCRIPTOR.message_types_by_name['GS2CMarryCancel'] = _GS2CMARRYCANCEL
DESCRIPTOR.message_types_by_name['GS2CSuccessDivorce'] = _GS2CSUCCESSDIVORCE
DESCRIPTOR.message_types_by_name['GS2CPickItemXT'] = _GS2CPICKITEMXT
DESCRIPTOR.message_types_by_name['MarryPlayer'] = _MARRYPLAYER
DESCRIPTOR.message_types_by_name['GS2CMarryWedding'] = _GS2CMARRYWEDDING
DESCRIPTOR.message_types_by_name['GS2CMarryWeddingEnd'] = _GS2CMARRYWEDDINGEND
DESCRIPTOR.message_types_by_name['GS2CTeamShowWedding'] = _GS2CTEAMSHOWWEDDING
DESCRIPTOR.message_types_by_name['GS2CMarryConfirmUI'] = _GS2CMARRYCONFIRMUI

GS2CMarryPayUI = _reflection.GeneratedProtocolMessageType('GS2CMarryPayUI', (_message.Message,), dict(
  DESCRIPTOR = _GS2CMARRYPAYUI,
  __module__ = 'marry_pb2'
  # @@protoc_insertion_point(class_scope:GS2CMarryPayUI)
  ))
_sym_db.RegisterMessage(GS2CMarryPayUI)

GS2CMarryCancel = _reflection.GeneratedProtocolMessageType('GS2CMarryCancel', (_message.Message,), dict(
  DESCRIPTOR = _GS2CMARRYCANCEL,
  __module__ = 'marry_pb2'
  # @@protoc_insertion_point(class_scope:GS2CMarryCancel)
  ))
_sym_db.RegisterMessage(GS2CMarryCancel)

GS2CSuccessDivorce = _reflection.GeneratedProtocolMessageType('GS2CSuccessDivorce', (_message.Message,), dict(
  DESCRIPTOR = _GS2CSUCCESSDIVORCE,
  __module__ = 'marry_pb2'
  # @@protoc_insertion_point(class_scope:GS2CSuccessDivorce)
  ))
_sym_db.RegisterMessage(GS2CSuccessDivorce)

GS2CPickItemXT = _reflection.GeneratedProtocolMessageType('GS2CPickItemXT', (_message.Message,), dict(
  DESCRIPTOR = _GS2CPICKITEMXT,
  __module__ = 'marry_pb2'
  # @@protoc_insertion_point(class_scope:GS2CPickItemXT)
  ))
_sym_db.RegisterMessage(GS2CPickItemXT)

MarryPlayer = _reflection.GeneratedProtocolMessageType('MarryPlayer', (_message.Message,), dict(
  DESCRIPTOR = _MARRYPLAYER,
  __module__ = 'marry_pb2'
  # @@protoc_insertion_point(class_scope:MarryPlayer)
  ))
_sym_db.RegisterMessage(MarryPlayer)

GS2CMarryWedding = _reflection.GeneratedProtocolMessageType('GS2CMarryWedding', (_message.Message,), dict(
  DESCRIPTOR = _GS2CMARRYWEDDING,
  __module__ = 'marry_pb2'
  # @@protoc_insertion_point(class_scope:GS2CMarryWedding)
  ))
_sym_db.RegisterMessage(GS2CMarryWedding)

GS2CMarryWeddingEnd = _reflection.GeneratedProtocolMessageType('GS2CMarryWeddingEnd', (_message.Message,), dict(
  DESCRIPTOR = _GS2CMARRYWEDDINGEND,
  __module__ = 'marry_pb2'
  # @@protoc_insertion_point(class_scope:GS2CMarryWeddingEnd)
  ))
_sym_db.RegisterMessage(GS2CMarryWeddingEnd)

GS2CTeamShowWedding = _reflection.GeneratedProtocolMessageType('GS2CTeamShowWedding', (_message.Message,), dict(
  DESCRIPTOR = _GS2CTEAMSHOWWEDDING,
  __module__ = 'marry_pb2'
  # @@protoc_insertion_point(class_scope:GS2CTeamShowWedding)
  ))
_sym_db.RegisterMessage(GS2CTeamShowWedding)

GS2CMarryConfirmUI = _reflection.GeneratedProtocolMessageType('GS2CMarryConfirmUI', (_message.Message,), dict(
  DESCRIPTOR = _GS2CMARRYCONFIRMUI,
  __module__ = 'marry_pb2'
  # @@protoc_insertion_point(class_scope:GS2CMarryConfirmUI)
  ))
_sym_db.RegisterMessage(GS2CMarryConfirmUI)


# @@protoc_insertion_point(module_scope)
