# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: npc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import common_pb2 as base_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='npc.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\tnpc.proto\x1a\x11\x62\x61se/common.proto\"\xaa\x01\n\nGS2CNpcSay\x12\x12\n\nsessionidx\x18\x01 \x01(\r\x12\r\n\x05npcid\x18\x02 \x01(\r\x12#\n\nmodel_info\x18\x03 \x01(\x0b\x32\x0f.base.ModelInfo\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x0c\n\x04text\x18\x05 \x01(\t\x12\x0c\n\x04type\x18\x06 \x01(\r\x12\x0b\n\x03lv2\x18\x07 \x01(\r\x12\x0c\n\x04time\x18\x08 \x01(\r\x12\x0f\n\x07\x64\x65\x66\x61ult\x18\t \x01(\r')
  ,
  dependencies=[base_dot_common__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GS2CNPCSAY = _descriptor.Descriptor(
  name='GS2CNpcSay',
  full_name='GS2CNpcSay',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sessionidx', full_name='GS2CNpcSay.sessionidx', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='npcid', full_name='GS2CNpcSay.npcid', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model_info', full_name='GS2CNpcSay.model_info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='GS2CNpcSay.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text', full_name='GS2CNpcSay.text', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='GS2CNpcSay.type', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lv2', full_name='GS2CNpcSay.lv2', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='GS2CNpcSay.time', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='default', full_name='GS2CNpcSay.default', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=203,
)

_GS2CNPCSAY.fields_by_name['model_info'].message_type = base_dot_common__pb2._MODELINFO
DESCRIPTOR.message_types_by_name['GS2CNpcSay'] = _GS2CNPCSAY

GS2CNpcSay = _reflection.GeneratedProtocolMessageType('GS2CNpcSay', (_message.Message,), dict(
  DESCRIPTOR = _GS2CNPCSAY,
  __module__ = 'npc_pb2'
  # @@protoc_insertion_point(class_scope:GS2CNpcSay)
  ))
_sym_db.RegisterMessage(GS2CNpcSay)


# @@protoc_insertion_point(module_scope)
