# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ride.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import common_pb2 as base_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ride.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\nride.proto\x1a\x11\x62\x61se/common.proto\"R\n\rRideSkillInfo\x12\n\n\x02sk\x18\x01 \x01(\r\x12\r\n\x05level\x18\x02 \x01(\r\x12\x0c\n\x04type\x18\x03 \x01(\r\x12\x0b\n\x03row\x18\x04 \x01(\r\x12\x0b\n\x03\x63ol\x18\x05 \x01(\r\"&\n\x07PosInfo\x12\x0b\n\x03pos\x18\x01 \x01(\r\x12\x0e\n\x06summon\x18\x02 \x01(\r\"\xa0\x01\n\x08RideInfo\x12\x0f\n\x07ride_id\x18\x01 \x01(\r\x12\x10\n\x08got_time\x18\x02 \x01(\r\x12\x11\n\tleft_time\x18\x03 \x01(\x05\x12\x19\n\x07summons\x18\x04 \x03(\x0b\x32\x08.PosInfo\x12\x1e\n\x06wenshi\x18\x05 \x03(\x0b\x32\x0e.base.ItemInfo\x12\r\n\x05skill\x18\x06 \x01(\r\x12\x14\n\x0cskill_effect\x18\x07 \x01(\r\"\xf2\x01\n\x0ePlayerRideInfo\x12\x0c\n\x04mask\x18\x01 \x01(\t\x12\r\n\x05grade\x18\x02 \x01(\r\x12\x0b\n\x03\x65xp\x18\x03 \x01(\r\x12\r\n\x05point\x18\x04 \x01(\r\x12\x10\n\x08use_ride\x18\x05 \x01(\r\x12\x15\n\rchoose_skills\x18\x06 \x03(\r\x12\x10\n\x08learn_sk\x18\x07 \x01(\r\x12\x1e\n\x06skills\x18\x08 \x03(\x0b\x32\x0e.RideSkillInfo\x12\x1d\n\nride_infos\x18\t \x03(\x0b\x32\t.RideInfo\x12\x1e\n\x05\x61ttrs\x18\n \x03(\x0b\x32\x0f.base.ApplyInfo\x12\r\n\x05score\x18\x0b \x01(\r\"3\n\x12GS2CPlayerRideInfo\x12\x1d\n\x04info\x18\x01 \x01(\x0b\x32\x0f.PlayerRideInfo\"+\n\x0bGS2CAddRide\x12\x1c\n\tride_info\x18\x01 \x01(\x0b\x32\t.RideInfo\"!\n\x0eGS2CDeleteRide\x12\x0f\n\x07ride_id\x18\x01 \x01(\r\".\n\x0eGS2CUpdateRide\x12\x1c\n\tride_info\x18\x01 \x01(\x0b\x32\t.RideInfo\"$\n\x11GS2CUpdateUseRide\x12\x0f\n\x07ride_id\x18\x01 \x01(\r\"$\n\x13GS2CShowRandomSkill\x12\r\n\x05skill\x18\x01 \x01(\r\"D\n\x12GS2CResetSKillInfo\x12\x10\n\x08\x63ost_exp\x18\x01 \x01(\r\x12\r\n\x05grade\x18\x02 \x01(\r\x12\r\n\x05point\x18\x03 \x01(\r')
  ,
  dependencies=[base_dot_common__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RIDESKILLINFO = _descriptor.Descriptor(
  name='RideSkillInfo',
  full_name='RideSkillInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sk', full_name='RideSkillInfo.sk', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='RideSkillInfo.level', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='RideSkillInfo.type', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='row', full_name='RideSkillInfo.row', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='col', full_name='RideSkillInfo.col', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=115,
)


_POSINFO = _descriptor.Descriptor(
  name='PosInfo',
  full_name='PosInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos', full_name='PosInfo.pos', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='summon', full_name='PosInfo.summon', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=155,
)


_RIDEINFO = _descriptor.Descriptor(
  name='RideInfo',
  full_name='RideInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ride_id', full_name='RideInfo.ride_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='got_time', full_name='RideInfo.got_time', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='left_time', full_name='RideInfo.left_time', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='summons', full_name='RideInfo.summons', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wenshi', full_name='RideInfo.wenshi', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='skill', full_name='RideInfo.skill', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='skill_effect', full_name='RideInfo.skill_effect', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=318,
)


_PLAYERRIDEINFO = _descriptor.Descriptor(
  name='PlayerRideInfo',
  full_name='PlayerRideInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mask', full_name='PlayerRideInfo.mask', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='grade', full_name='PlayerRideInfo.grade', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exp', full_name='PlayerRideInfo.exp', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='point', full_name='PlayerRideInfo.point', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='use_ride', full_name='PlayerRideInfo.use_ride', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='choose_skills', full_name='PlayerRideInfo.choose_skills', index=5,
      number=6, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='learn_sk', full_name='PlayerRideInfo.learn_sk', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='skills', full_name='PlayerRideInfo.skills', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ride_infos', full_name='PlayerRideInfo.ride_infos', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attrs', full_name='PlayerRideInfo.attrs', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='score', full_name='PlayerRideInfo.score', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=321,
  serialized_end=563,
)


_GS2CPLAYERRIDEINFO = _descriptor.Descriptor(
  name='GS2CPlayerRideInfo',
  full_name='GS2CPlayerRideInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='GS2CPlayerRideInfo.info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=565,
  serialized_end=616,
)


_GS2CADDRIDE = _descriptor.Descriptor(
  name='GS2CAddRide',
  full_name='GS2CAddRide',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ride_info', full_name='GS2CAddRide.ride_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=618,
  serialized_end=661,
)


_GS2CDELETERIDE = _descriptor.Descriptor(
  name='GS2CDeleteRide',
  full_name='GS2CDeleteRide',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ride_id', full_name='GS2CDeleteRide.ride_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=663,
  serialized_end=696,
)


_GS2CUPDATERIDE = _descriptor.Descriptor(
  name='GS2CUpdateRide',
  full_name='GS2CUpdateRide',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ride_info', full_name='GS2CUpdateRide.ride_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=698,
  serialized_end=744,
)


_GS2CUPDATEUSERIDE = _descriptor.Descriptor(
  name='GS2CUpdateUseRide',
  full_name='GS2CUpdateUseRide',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ride_id', full_name='GS2CUpdateUseRide.ride_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=746,
  serialized_end=782,
)


_GS2CSHOWRANDOMSKILL = _descriptor.Descriptor(
  name='GS2CShowRandomSkill',
  full_name='GS2CShowRandomSkill',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='skill', full_name='GS2CShowRandomSkill.skill', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=784,
  serialized_end=820,
)


_GS2CRESETSKILLINFO = _descriptor.Descriptor(
  name='GS2CResetSKillInfo',
  full_name='GS2CResetSKillInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cost_exp', full_name='GS2CResetSKillInfo.cost_exp', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='grade', full_name='GS2CResetSKillInfo.grade', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='point', full_name='GS2CResetSKillInfo.point', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=822,
  serialized_end=890,
)

_RIDEINFO.fields_by_name['summons'].message_type = _POSINFO
_RIDEINFO.fields_by_name['wenshi'].message_type = base_dot_common__pb2._ITEMINFO
_PLAYERRIDEINFO.fields_by_name['skills'].message_type = _RIDESKILLINFO
_PLAYERRIDEINFO.fields_by_name['ride_infos'].message_type = _RIDEINFO
_PLAYERRIDEINFO.fields_by_name['attrs'].message_type = base_dot_common__pb2._APPLYINFO
_GS2CPLAYERRIDEINFO.fields_by_name['info'].message_type = _PLAYERRIDEINFO
_GS2CADDRIDE.fields_by_name['ride_info'].message_type = _RIDEINFO
_GS2CUPDATERIDE.fields_by_name['ride_info'].message_type = _RIDEINFO
DESCRIPTOR.message_types_by_name['RideSkillInfo'] = _RIDESKILLINFO
DESCRIPTOR.message_types_by_name['PosInfo'] = _POSINFO
DESCRIPTOR.message_types_by_name['RideInfo'] = _RIDEINFO
DESCRIPTOR.message_types_by_name['PlayerRideInfo'] = _PLAYERRIDEINFO
DESCRIPTOR.message_types_by_name['GS2CPlayerRideInfo'] = _GS2CPLAYERRIDEINFO
DESCRIPTOR.message_types_by_name['GS2CAddRide'] = _GS2CADDRIDE
DESCRIPTOR.message_types_by_name['GS2CDeleteRide'] = _GS2CDELETERIDE
DESCRIPTOR.message_types_by_name['GS2CUpdateRide'] = _GS2CUPDATERIDE
DESCRIPTOR.message_types_by_name['GS2CUpdateUseRide'] = _GS2CUPDATEUSERIDE
DESCRIPTOR.message_types_by_name['GS2CShowRandomSkill'] = _GS2CSHOWRANDOMSKILL
DESCRIPTOR.message_types_by_name['GS2CResetSKillInfo'] = _GS2CRESETSKILLINFO

RideSkillInfo = _reflection.GeneratedProtocolMessageType('RideSkillInfo', (_message.Message,), dict(
  DESCRIPTOR = _RIDESKILLINFO,
  __module__ = 'ride_pb2'
  # @@protoc_insertion_point(class_scope:RideSkillInfo)
  ))
_sym_db.RegisterMessage(RideSkillInfo)

PosInfo = _reflection.GeneratedProtocolMessageType('PosInfo', (_message.Message,), dict(
  DESCRIPTOR = _POSINFO,
  __module__ = 'ride_pb2'
  # @@protoc_insertion_point(class_scope:PosInfo)
  ))
_sym_db.RegisterMessage(PosInfo)

RideInfo = _reflection.GeneratedProtocolMessageType('RideInfo', (_message.Message,), dict(
  DESCRIPTOR = _RIDEINFO,
  __module__ = 'ride_pb2'
  # @@protoc_insertion_point(class_scope:RideInfo)
  ))
_sym_db.RegisterMessage(RideInfo)

PlayerRideInfo = _reflection.GeneratedProtocolMessageType('PlayerRideInfo', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERRIDEINFO,
  __module__ = 'ride_pb2'
  # @@protoc_insertion_point(class_scope:PlayerRideInfo)
  ))
_sym_db.RegisterMessage(PlayerRideInfo)

GS2CPlayerRideInfo = _reflection.GeneratedProtocolMessageType('GS2CPlayerRideInfo', (_message.Message,), dict(
  DESCRIPTOR = _GS2CPLAYERRIDEINFO,
  __module__ = 'ride_pb2'
  # @@protoc_insertion_point(class_scope:GS2CPlayerRideInfo)
  ))
_sym_db.RegisterMessage(GS2CPlayerRideInfo)

GS2CAddRide = _reflection.GeneratedProtocolMessageType('GS2CAddRide', (_message.Message,), dict(
  DESCRIPTOR = _GS2CADDRIDE,
  __module__ = 'ride_pb2'
  # @@protoc_insertion_point(class_scope:GS2CAddRide)
  ))
_sym_db.RegisterMessage(GS2CAddRide)

GS2CDeleteRide = _reflection.GeneratedProtocolMessageType('GS2CDeleteRide', (_message.Message,), dict(
  DESCRIPTOR = _GS2CDELETERIDE,
  __module__ = 'ride_pb2'
  # @@protoc_insertion_point(class_scope:GS2CDeleteRide)
  ))
_sym_db.RegisterMessage(GS2CDeleteRide)

GS2CUpdateRide = _reflection.GeneratedProtocolMessageType('GS2CUpdateRide', (_message.Message,), dict(
  DESCRIPTOR = _GS2CUPDATERIDE,
  __module__ = 'ride_pb2'
  # @@protoc_insertion_point(class_scope:GS2CUpdateRide)
  ))
_sym_db.RegisterMessage(GS2CUpdateRide)

GS2CUpdateUseRide = _reflection.GeneratedProtocolMessageType('GS2CUpdateUseRide', (_message.Message,), dict(
  DESCRIPTOR = _GS2CUPDATEUSERIDE,
  __module__ = 'ride_pb2'
  # @@protoc_insertion_point(class_scope:GS2CUpdateUseRide)
  ))
_sym_db.RegisterMessage(GS2CUpdateUseRide)

GS2CShowRandomSkill = _reflection.GeneratedProtocolMessageType('GS2CShowRandomSkill', (_message.Message,), dict(
  DESCRIPTOR = _GS2CSHOWRANDOMSKILL,
  __module__ = 'ride_pb2'
  # @@protoc_insertion_point(class_scope:GS2CShowRandomSkill)
  ))
_sym_db.RegisterMessage(GS2CShowRandomSkill)

GS2CResetSKillInfo = _reflection.GeneratedProtocolMessageType('GS2CResetSKillInfo', (_message.Message,), dict(
  DESCRIPTOR = _GS2CRESETSKILLINFO,
  __module__ = 'ride_pb2'
  # @@protoc_insertion_point(class_scope:GS2CResetSKillInfo)
  ))
_sym_db.RegisterMessage(GS2CResetSKillInfo)


# @@protoc_insertion_point(module_scope)
