# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sysopen.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sysopen.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\rsysopen.proto\"$\n\x10GS2CLoginOpenSys\x12\x10\n\x08open_sys\x18\x01 \x03(\t\"(\n\x0bSysOpenInfo\x12\x0b\n\x03sys\x18\x01 \x01(\t\x12\x0c\n\x04open\x18\x02 \x01(\r\"2\n\x11GS2COpenSysChange\x12\x1d\n\x07\x63hanges\x18\x01 \x03(\x0b\x32\x0c.SysOpenInfo\"@\n\rSysSwitchInfo\x12\x0f\n\x07systype\x18\x01 \x01(\r\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\r\x12\r\n\x05state\x18\x03 \x01(\r\"0\n\rGS2CSysSwitch\x12\x1f\n\x07syslist\x18\x01 \x03(\x0b\x32\x0e.SysSwitchInfo')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GS2CLOGINOPENSYS = _descriptor.Descriptor(
  name='GS2CLoginOpenSys',
  full_name='GS2CLoginOpenSys',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='open_sys', full_name='GS2CLoginOpenSys.open_sys', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=53,
)


_SYSOPENINFO = _descriptor.Descriptor(
  name='SysOpenInfo',
  full_name='SysOpenInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sys', full_name='SysOpenInfo.sys', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='open', full_name='SysOpenInfo.open', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=95,
)


_GS2COPENSYSCHANGE = _descriptor.Descriptor(
  name='GS2COpenSysChange',
  full_name='GS2COpenSysChange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='changes', full_name='GS2COpenSysChange.changes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=147,
)


_SYSSWITCHINFO = _descriptor.Descriptor(
  name='SysSwitchInfo',
  full_name='SysSwitchInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='systype', full_name='SysSwitchInfo.systype', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channel', full_name='SysSwitchInfo.channel', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='SysSwitchInfo.state', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=213,
)


_GS2CSYSSWITCH = _descriptor.Descriptor(
  name='GS2CSysSwitch',
  full_name='GS2CSysSwitch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='syslist', full_name='GS2CSysSwitch.syslist', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=263,
)

_GS2COPENSYSCHANGE.fields_by_name['changes'].message_type = _SYSOPENINFO
_GS2CSYSSWITCH.fields_by_name['syslist'].message_type = _SYSSWITCHINFO
DESCRIPTOR.message_types_by_name['GS2CLoginOpenSys'] = _GS2CLOGINOPENSYS
DESCRIPTOR.message_types_by_name['SysOpenInfo'] = _SYSOPENINFO
DESCRIPTOR.message_types_by_name['GS2COpenSysChange'] = _GS2COPENSYSCHANGE
DESCRIPTOR.message_types_by_name['SysSwitchInfo'] = _SYSSWITCHINFO
DESCRIPTOR.message_types_by_name['GS2CSysSwitch'] = _GS2CSYSSWITCH

GS2CLoginOpenSys = _reflection.GeneratedProtocolMessageType('GS2CLoginOpenSys', (_message.Message,), dict(
  DESCRIPTOR = _GS2CLOGINOPENSYS,
  __module__ = 'sysopen_pb2'
  # @@protoc_insertion_point(class_scope:GS2CLoginOpenSys)
  ))
_sym_db.RegisterMessage(GS2CLoginOpenSys)

SysOpenInfo = _reflection.GeneratedProtocolMessageType('SysOpenInfo', (_message.Message,), dict(
  DESCRIPTOR = _SYSOPENINFO,
  __module__ = 'sysopen_pb2'
  # @@protoc_insertion_point(class_scope:SysOpenInfo)
  ))
_sym_db.RegisterMessage(SysOpenInfo)

GS2COpenSysChange = _reflection.GeneratedProtocolMessageType('GS2COpenSysChange', (_message.Message,), dict(
  DESCRIPTOR = _GS2COPENSYSCHANGE,
  __module__ = 'sysopen_pb2'
  # @@protoc_insertion_point(class_scope:GS2COpenSysChange)
  ))
_sym_db.RegisterMessage(GS2COpenSysChange)

SysSwitchInfo = _reflection.GeneratedProtocolMessageType('SysSwitchInfo', (_message.Message,), dict(
  DESCRIPTOR = _SYSSWITCHINFO,
  __module__ = 'sysopen_pb2'
  # @@protoc_insertion_point(class_scope:SysSwitchInfo)
  ))
_sym_db.RegisterMessage(SysSwitchInfo)

GS2CSysSwitch = _reflection.GeneratedProtocolMessageType('GS2CSysSwitch', (_message.Message,), dict(
  DESCRIPTOR = _GS2CSYSSWITCH,
  __module__ = 'sysopen_pb2'
  # @@protoc_insertion_point(class_scope:GS2CSysSwitch)
  ))
_sym_db.RegisterMessage(GS2CSysSwitch)


# @@protoc_insertion_point(module_scope)
