# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import common_pb2 as base_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\ntest.proto\x1a\x11\x62\x61se/common.proto\"e\n\x0bGS2CTestNet\x12\t\n\x01\x61\x18\x01 \x01(\r\x12\t\n\x01\x62\x18\x02 \x01(\r\x12\t\n\x01\x63\x18\x03 \x01(\r\x12\t\n\x01\x64\x18\x04 \x01(\r\x12\t\n\x01\x65\x18\x05 \x01(\t\x12\t\n\x01\x66\x18\x06 \x01(\t\x12\t\n\x01g\x18\x07 \x01(\t\x12\t\n\x01h\x18\x08 \x01(\t\"\x1e\n\x11GS2CTestBigPacket\x12\t\n\x01s\x18\x01 \x01(\t\"7\n\x14GS2CTestOnlineUpdate\x12\t\n\x01\x61\x18\x01 \x01(\r\x12\t\n\x01\x62\x18\x02 \x01(\t\x12\t\n\x01\x63\x18\x03 \x01(\r\"\x1e\n\x11GS2CTestOnlineAdd\x12\t\n\x01\x61\x18\x01 \x01(\r\"&\n\x0eGS2CTestEncode\x12\t\n\x01\x61\x18\x01 \x01(\r\x12\t\n\x01\x62\x18\x02 \x01(\t')
  ,
  dependencies=[base_dot_common__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GS2CTESTNET = _descriptor.Descriptor(
  name='GS2CTestNet',
  full_name='GS2CTestNet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='GS2CTestNet.a', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='b', full_name='GS2CTestNet.b', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='c', full_name='GS2CTestNet.c', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='d', full_name='GS2CTestNet.d', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='e', full_name='GS2CTestNet.e', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='f', full_name='GS2CTestNet.f', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='g', full_name='GS2CTestNet.g', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='h', full_name='GS2CTestNet.h', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=134,
)


_GS2CTESTBIGPACKET = _descriptor.Descriptor(
  name='GS2CTestBigPacket',
  full_name='GS2CTestBigPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='s', full_name='GS2CTestBigPacket.s', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=166,
)


_GS2CTESTONLINEUPDATE = _descriptor.Descriptor(
  name='GS2CTestOnlineUpdate',
  full_name='GS2CTestOnlineUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='GS2CTestOnlineUpdate.a', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='b', full_name='GS2CTestOnlineUpdate.b', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='c', full_name='GS2CTestOnlineUpdate.c', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=223,
)


_GS2CTESTONLINEADD = _descriptor.Descriptor(
  name='GS2CTestOnlineAdd',
  full_name='GS2CTestOnlineAdd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='GS2CTestOnlineAdd.a', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=255,
)


_GS2CTESTENCODE = _descriptor.Descriptor(
  name='GS2CTestEncode',
  full_name='GS2CTestEncode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='GS2CTestEncode.a', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='b', full_name='GS2CTestEncode.b', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=295,
)

DESCRIPTOR.message_types_by_name['GS2CTestNet'] = _GS2CTESTNET
DESCRIPTOR.message_types_by_name['GS2CTestBigPacket'] = _GS2CTESTBIGPACKET
DESCRIPTOR.message_types_by_name['GS2CTestOnlineUpdate'] = _GS2CTESTONLINEUPDATE
DESCRIPTOR.message_types_by_name['GS2CTestOnlineAdd'] = _GS2CTESTONLINEADD
DESCRIPTOR.message_types_by_name['GS2CTestEncode'] = _GS2CTESTENCODE

GS2CTestNet = _reflection.GeneratedProtocolMessageType('GS2CTestNet', (_message.Message,), dict(
  DESCRIPTOR = _GS2CTESTNET,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:GS2CTestNet)
  ))
_sym_db.RegisterMessage(GS2CTestNet)

GS2CTestBigPacket = _reflection.GeneratedProtocolMessageType('GS2CTestBigPacket', (_message.Message,), dict(
  DESCRIPTOR = _GS2CTESTBIGPACKET,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:GS2CTestBigPacket)
  ))
_sym_db.RegisterMessage(GS2CTestBigPacket)

GS2CTestOnlineUpdate = _reflection.GeneratedProtocolMessageType('GS2CTestOnlineUpdate', (_message.Message,), dict(
  DESCRIPTOR = _GS2CTESTONLINEUPDATE,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:GS2CTestOnlineUpdate)
  ))
_sym_db.RegisterMessage(GS2CTestOnlineUpdate)

GS2CTestOnlineAdd = _reflection.GeneratedProtocolMessageType('GS2CTestOnlineAdd', (_message.Message,), dict(
  DESCRIPTOR = _GS2CTESTONLINEADD,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:GS2CTestOnlineAdd)
  ))
_sym_db.RegisterMessage(GS2CTestOnlineAdd)

GS2CTestEncode = _reflection.GeneratedProtocolMessageType('GS2CTestEncode', (_message.Message,), dict(
  DESCRIPTOR = _GS2CTESTENCODE,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:GS2CTestEncode)
  ))
_sym_db.RegisterMessage(GS2CTestEncode)


# @@protoc_insertion_point(module_scope)
