# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: warehouse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import common_pb2 as base_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='warehouse.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0fwarehouse.proto\x1a\x11\x62\x61se/common.proto\"3\n\x11GS2CWareHouseInfo\x12\x0c\n\x04size\x18\x01 \x01(\r\x12\x10\n\x08namelist\x18\x02 \x03(\t\"S\n\x14GS2CRefreshWareHouse\x12\x0b\n\x03wid\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12 \n\x08itemdata\x18\x03 \x03(\x0b\x32\x0e.base.ItemInfo\".\n\x11GS2CWareHouseName\x12\x0b\n\x03wid\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\"E\n\x14GS2CAddWareHouseItem\x12\x0b\n\x03wid\x18\x01 \x01(\r\x12 \n\x08itemdata\x18\x02 \x01(\x0b\x32\x0e.base.ItemInfo\"3\n\x14GS2CDelWareHouseItem\x12\x0b\n\x03wid\x18\x01 \x01(\r\x12\x0e\n\x06itemid\x18\x02 \x01(\r\"A\n\x11GS2CWHItemArrange\x12\x0b\n\x03wid\x18\x01 \x01(\r\x12\x1f\n\x08pos_info\x18\x02 \x03(\x0b\x32\r.base.ItemPos\"?\n\x10GS2CWHItemAmount\x12\x0b\n\x03wid\x18\x01 \x01(\r\x12\x0e\n\x06itemid\x18\x02 \x01(\r\x12\x0e\n\x06\x61mount\x18\x03 \x01(\r\"A\n\x10GS2CUpdateWHItem\x12\x0b\n\x03wid\x18\x01 \x01(\r\x12 \n\x08itemdata\x18\x02 \x01(\x0b\x32\x0e.base.ItemInfo')
  ,
  dependencies=[base_dot_common__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GS2CWAREHOUSEINFO = _descriptor.Descriptor(
  name='GS2CWareHouseInfo',
  full_name='GS2CWareHouseInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='GS2CWareHouseInfo.size', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='namelist', full_name='GS2CWareHouseInfo.namelist', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=89,
)


_GS2CREFRESHWAREHOUSE = _descriptor.Descriptor(
  name='GS2CRefreshWareHouse',
  full_name='GS2CRefreshWareHouse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wid', full_name='GS2CRefreshWareHouse.wid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='GS2CRefreshWareHouse.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='itemdata', full_name='GS2CRefreshWareHouse.itemdata', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=174,
)


_GS2CWAREHOUSENAME = _descriptor.Descriptor(
  name='GS2CWareHouseName',
  full_name='GS2CWareHouseName',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wid', full_name='GS2CWareHouseName.wid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='GS2CWareHouseName.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=222,
)


_GS2CADDWAREHOUSEITEM = _descriptor.Descriptor(
  name='GS2CAddWareHouseItem',
  full_name='GS2CAddWareHouseItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wid', full_name='GS2CAddWareHouseItem.wid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='itemdata', full_name='GS2CAddWareHouseItem.itemdata', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=293,
)


_GS2CDELWAREHOUSEITEM = _descriptor.Descriptor(
  name='GS2CDelWareHouseItem',
  full_name='GS2CDelWareHouseItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wid', full_name='GS2CDelWareHouseItem.wid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='itemid', full_name='GS2CDelWareHouseItem.itemid', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=295,
  serialized_end=346,
)


_GS2CWHITEMARRANGE = _descriptor.Descriptor(
  name='GS2CWHItemArrange',
  full_name='GS2CWHItemArrange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wid', full_name='GS2CWHItemArrange.wid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pos_info', full_name='GS2CWHItemArrange.pos_info', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=413,
)


_GS2CWHITEMAMOUNT = _descriptor.Descriptor(
  name='GS2CWHItemAmount',
  full_name='GS2CWHItemAmount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wid', full_name='GS2CWHItemAmount.wid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='itemid', full_name='GS2CWHItemAmount.itemid', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='amount', full_name='GS2CWHItemAmount.amount', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=415,
  serialized_end=478,
)


_GS2CUPDATEWHITEM = _descriptor.Descriptor(
  name='GS2CUpdateWHItem',
  full_name='GS2CUpdateWHItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wid', full_name='GS2CUpdateWHItem.wid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='itemdata', full_name='GS2CUpdateWHItem.itemdata', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=480,
  serialized_end=545,
)

_GS2CREFRESHWAREHOUSE.fields_by_name['itemdata'].message_type = base_dot_common__pb2._ITEMINFO
_GS2CADDWAREHOUSEITEM.fields_by_name['itemdata'].message_type = base_dot_common__pb2._ITEMINFO
_GS2CWHITEMARRANGE.fields_by_name['pos_info'].message_type = base_dot_common__pb2._ITEMPOS
_GS2CUPDATEWHITEM.fields_by_name['itemdata'].message_type = base_dot_common__pb2._ITEMINFO
DESCRIPTOR.message_types_by_name['GS2CWareHouseInfo'] = _GS2CWAREHOUSEINFO
DESCRIPTOR.message_types_by_name['GS2CRefreshWareHouse'] = _GS2CREFRESHWAREHOUSE
DESCRIPTOR.message_types_by_name['GS2CWareHouseName'] = _GS2CWAREHOUSENAME
DESCRIPTOR.message_types_by_name['GS2CAddWareHouseItem'] = _GS2CADDWAREHOUSEITEM
DESCRIPTOR.message_types_by_name['GS2CDelWareHouseItem'] = _GS2CDELWAREHOUSEITEM
DESCRIPTOR.message_types_by_name['GS2CWHItemArrange'] = _GS2CWHITEMARRANGE
DESCRIPTOR.message_types_by_name['GS2CWHItemAmount'] = _GS2CWHITEMAMOUNT
DESCRIPTOR.message_types_by_name['GS2CUpdateWHItem'] = _GS2CUPDATEWHITEM

GS2CWareHouseInfo = _reflection.GeneratedProtocolMessageType('GS2CWareHouseInfo', (_message.Message,), dict(
  DESCRIPTOR = _GS2CWAREHOUSEINFO,
  __module__ = 'warehouse_pb2'
  # @@protoc_insertion_point(class_scope:GS2CWareHouseInfo)
  ))
_sym_db.RegisterMessage(GS2CWareHouseInfo)

GS2CRefreshWareHouse = _reflection.GeneratedProtocolMessageType('GS2CRefreshWareHouse', (_message.Message,), dict(
  DESCRIPTOR = _GS2CREFRESHWAREHOUSE,
  __module__ = 'warehouse_pb2'
  # @@protoc_insertion_point(class_scope:GS2CRefreshWareHouse)
  ))
_sym_db.RegisterMessage(GS2CRefreshWareHouse)

GS2CWareHouseName = _reflection.GeneratedProtocolMessageType('GS2CWareHouseName', (_message.Message,), dict(
  DESCRIPTOR = _GS2CWAREHOUSENAME,
  __module__ = 'warehouse_pb2'
  # @@protoc_insertion_point(class_scope:GS2CWareHouseName)
  ))
_sym_db.RegisterMessage(GS2CWareHouseName)

GS2CAddWareHouseItem = _reflection.GeneratedProtocolMessageType('GS2CAddWareHouseItem', (_message.Message,), dict(
  DESCRIPTOR = _GS2CADDWAREHOUSEITEM,
  __module__ = 'warehouse_pb2'
  # @@protoc_insertion_point(class_scope:GS2CAddWareHouseItem)
  ))
_sym_db.RegisterMessage(GS2CAddWareHouseItem)

GS2CDelWareHouseItem = _reflection.GeneratedProtocolMessageType('GS2CDelWareHouseItem', (_message.Message,), dict(
  DESCRIPTOR = _GS2CDELWAREHOUSEITEM,
  __module__ = 'warehouse_pb2'
  # @@protoc_insertion_point(class_scope:GS2CDelWareHouseItem)
  ))
_sym_db.RegisterMessage(GS2CDelWareHouseItem)

GS2CWHItemArrange = _reflection.GeneratedProtocolMessageType('GS2CWHItemArrange', (_message.Message,), dict(
  DESCRIPTOR = _GS2CWHITEMARRANGE,
  __module__ = 'warehouse_pb2'
  # @@protoc_insertion_point(class_scope:GS2CWHItemArrange)
  ))
_sym_db.RegisterMessage(GS2CWHItemArrange)

GS2CWHItemAmount = _reflection.GeneratedProtocolMessageType('GS2CWHItemAmount', (_message.Message,), dict(
  DESCRIPTOR = _GS2CWHITEMAMOUNT,
  __module__ = 'warehouse_pb2'
  # @@protoc_insertion_point(class_scope:GS2CWHItemAmount)
  ))
_sym_db.RegisterMessage(GS2CWHItemAmount)

GS2CUpdateWHItem = _reflection.GeneratedProtocolMessageType('GS2CUpdateWHItem', (_message.Message,), dict(
  DESCRIPTOR = _GS2CUPDATEWHITEM,
  __module__ = 'warehouse_pb2'
  # @@protoc_insertion_point(class_scope:GS2CUpdateWHItem)
  ))
_sym_db.RegisterMessage(GS2CUpdateWHItem)


# @@protoc_insertion_point(module_scope)
