# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: artifact.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='artifact.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0e\x61rtifact.proto\"\x14\n\x12\x43\x32GSArtifactOpenUI\"*\n\x16\x43\x32GSArtifactUpgradeUse\x12\x10\n\x08goldcoin\x18\x01 \x01(\r\"(\n\x14\x43\x32GSArtifactStrength\x12\x10\n\x08goldcoin\x18\x01 \x01(\r\"?\n\x18\x43\x32GSArtifactSpiritWakeup\x12\x11\n\tspirit_id\x18\x01 \x01(\r\x12\x10\n\x08goldcoin\x18\x02 \x01(\r\"C\n\x1c\x43\x32GSArtifactSpiritResetSkill\x12\x11\n\tspirit_id\x18\x01 \x01(\r\x12\x10\n\x08goldcoin\x18\x02 \x01(\r\"0\n\x1b\x43\x32GSArtifactSpiritSaveSkill\x12\x11\n\tspirit_id\x18\x01 \x01(\r\"0\n\x1b\x43\x32GSArtifactSetFollowSpirit\x12\x11\n\tspirit_id\x18\x01 \x01(\r\"/\n\x1a\x43\x32GSArtifactSetFightSpirit\x12\x11\n\tspirit_id\x18\x01 \x01(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_C2GSARTIFACTOPENUI = _descriptor.Descriptor(
  name='C2GSArtifactOpenUI',
  full_name='C2GSArtifactOpenUI',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=38,
)


_C2GSARTIFACTUPGRADEUSE = _descriptor.Descriptor(
  name='C2GSArtifactUpgradeUse',
  full_name='C2GSArtifactUpgradeUse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='goldcoin', full_name='C2GSArtifactUpgradeUse.goldcoin', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=82,
)


_C2GSARTIFACTSTRENGTH = _descriptor.Descriptor(
  name='C2GSArtifactStrength',
  full_name='C2GSArtifactStrength',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='goldcoin', full_name='C2GSArtifactStrength.goldcoin', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=124,
)


_C2GSARTIFACTSPIRITWAKEUP = _descriptor.Descriptor(
  name='C2GSArtifactSpiritWakeup',
  full_name='C2GSArtifactSpiritWakeup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spirit_id', full_name='C2GSArtifactSpiritWakeup.spirit_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='goldcoin', full_name='C2GSArtifactSpiritWakeup.goldcoin', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=189,
)


_C2GSARTIFACTSPIRITRESETSKILL = _descriptor.Descriptor(
  name='C2GSArtifactSpiritResetSkill',
  full_name='C2GSArtifactSpiritResetSkill',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spirit_id', full_name='C2GSArtifactSpiritResetSkill.spirit_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='goldcoin', full_name='C2GSArtifactSpiritResetSkill.goldcoin', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=258,
)


_C2GSARTIFACTSPIRITSAVESKILL = _descriptor.Descriptor(
  name='C2GSArtifactSpiritSaveSkill',
  full_name='C2GSArtifactSpiritSaveSkill',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spirit_id', full_name='C2GSArtifactSpiritSaveSkill.spirit_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=308,
)


_C2GSARTIFACTSETFOLLOWSPIRIT = _descriptor.Descriptor(
  name='C2GSArtifactSetFollowSpirit',
  full_name='C2GSArtifactSetFollowSpirit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spirit_id', full_name='C2GSArtifactSetFollowSpirit.spirit_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=310,
  serialized_end=358,
)


_C2GSARTIFACTSETFIGHTSPIRIT = _descriptor.Descriptor(
  name='C2GSArtifactSetFightSpirit',
  full_name='C2GSArtifactSetFightSpirit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spirit_id', full_name='C2GSArtifactSetFightSpirit.spirit_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=360,
  serialized_end=407,
)

DESCRIPTOR.message_types_by_name['C2GSArtifactOpenUI'] = _C2GSARTIFACTOPENUI
DESCRIPTOR.message_types_by_name['C2GSArtifactUpgradeUse'] = _C2GSARTIFACTUPGRADEUSE
DESCRIPTOR.message_types_by_name['C2GSArtifactStrength'] = _C2GSARTIFACTSTRENGTH
DESCRIPTOR.message_types_by_name['C2GSArtifactSpiritWakeup'] = _C2GSARTIFACTSPIRITWAKEUP
DESCRIPTOR.message_types_by_name['C2GSArtifactSpiritResetSkill'] = _C2GSARTIFACTSPIRITRESETSKILL
DESCRIPTOR.message_types_by_name['C2GSArtifactSpiritSaveSkill'] = _C2GSARTIFACTSPIRITSAVESKILL
DESCRIPTOR.message_types_by_name['C2GSArtifactSetFollowSpirit'] = _C2GSARTIFACTSETFOLLOWSPIRIT
DESCRIPTOR.message_types_by_name['C2GSArtifactSetFightSpirit'] = _C2GSARTIFACTSETFIGHTSPIRIT

C2GSArtifactOpenUI = _reflection.GeneratedProtocolMessageType('C2GSArtifactOpenUI', (_message.Message,), dict(
  DESCRIPTOR = _C2GSARTIFACTOPENUI,
  __module__ = 'artifact_pb2'
  # @@protoc_insertion_point(class_scope:C2GSArtifactOpenUI)
  ))
_sym_db.RegisterMessage(C2GSArtifactOpenUI)

C2GSArtifactUpgradeUse = _reflection.GeneratedProtocolMessageType('C2GSArtifactUpgradeUse', (_message.Message,), dict(
  DESCRIPTOR = _C2GSARTIFACTUPGRADEUSE,
  __module__ = 'artifact_pb2'
  # @@protoc_insertion_point(class_scope:C2GSArtifactUpgradeUse)
  ))
_sym_db.RegisterMessage(C2GSArtifactUpgradeUse)

C2GSArtifactStrength = _reflection.GeneratedProtocolMessageType('C2GSArtifactStrength', (_message.Message,), dict(
  DESCRIPTOR = _C2GSARTIFACTSTRENGTH,
  __module__ = 'artifact_pb2'
  # @@protoc_insertion_point(class_scope:C2GSArtifactStrength)
  ))
_sym_db.RegisterMessage(C2GSArtifactStrength)

C2GSArtifactSpiritWakeup = _reflection.GeneratedProtocolMessageType('C2GSArtifactSpiritWakeup', (_message.Message,), dict(
  DESCRIPTOR = _C2GSARTIFACTSPIRITWAKEUP,
  __module__ = 'artifact_pb2'
  # @@protoc_insertion_point(class_scope:C2GSArtifactSpiritWakeup)
  ))
_sym_db.RegisterMessage(C2GSArtifactSpiritWakeup)

C2GSArtifactSpiritResetSkill = _reflection.GeneratedProtocolMessageType('C2GSArtifactSpiritResetSkill', (_message.Message,), dict(
  DESCRIPTOR = _C2GSARTIFACTSPIRITRESETSKILL,
  __module__ = 'artifact_pb2'
  # @@protoc_insertion_point(class_scope:C2GSArtifactSpiritResetSkill)
  ))
_sym_db.RegisterMessage(C2GSArtifactSpiritResetSkill)

C2GSArtifactSpiritSaveSkill = _reflection.GeneratedProtocolMessageType('C2GSArtifactSpiritSaveSkill', (_message.Message,), dict(
  DESCRIPTOR = _C2GSARTIFACTSPIRITSAVESKILL,
  __module__ = 'artifact_pb2'
  # @@protoc_insertion_point(class_scope:C2GSArtifactSpiritSaveSkill)
  ))
_sym_db.RegisterMessage(C2GSArtifactSpiritSaveSkill)

C2GSArtifactSetFollowSpirit = _reflection.GeneratedProtocolMessageType('C2GSArtifactSetFollowSpirit', (_message.Message,), dict(
  DESCRIPTOR = _C2GSARTIFACTSETFOLLOWSPIRIT,
  __module__ = 'artifact_pb2'
  # @@protoc_insertion_point(class_scope:C2GSArtifactSetFollowSpirit)
  ))
_sym_db.RegisterMessage(C2GSArtifactSetFollowSpirit)

C2GSArtifactSetFightSpirit = _reflection.GeneratedProtocolMessageType('C2GSArtifactSetFightSpirit', (_message.Message,), dict(
  DESCRIPTOR = _C2GSARTIFACTSETFIGHTSPIRIT,
  __module__ = 'artifact_pb2'
  # @@protoc_insertion_point(class_scope:C2GSArtifactSetFightSpirit)
  ))
_sym_db.RegisterMessage(C2GSArtifactSetFightSpirit)


# @@protoc_insertion_point(module_scope)
