# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: engage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='engage.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0c\x65ngage.proto\"#\n\x13\x43\x32GSEngageCondition\x12\x0c\n\x04type\x18\x01 \x01(\r\"\x1f\n\x0f\x43\x32GSStartEngage\x12\x0c\n\x04type\x18\x01 \x01(\r\"\"\n\x11\x43\x32GSConfirmEngage\x12\r\n\x05\x61gree\x18\x01 \x01(\r\"!\n\x11\x43\x32GSSetEngageText\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x14\n\x12\x43\x32GSDissolveEngage\"\x12\n\x10\x43\x32GSCancelEngage')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_C2GSENGAGECONDITION = _descriptor.Descriptor(
  name='C2GSEngageCondition',
  full_name='C2GSEngageCondition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='C2GSEngageCondition.type', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=51,
)


_C2GSSTARTENGAGE = _descriptor.Descriptor(
  name='C2GSStartEngage',
  full_name='C2GSStartEngage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='C2GSStartEngage.type', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=84,
)


_C2GSCONFIRMENGAGE = _descriptor.Descriptor(
  name='C2GSConfirmEngage',
  full_name='C2GSConfirmEngage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agree', full_name='C2GSConfirmEngage.agree', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=120,
)


_C2GSSETENGAGETEXT = _descriptor.Descriptor(
  name='C2GSSetEngageText',
  full_name='C2GSSetEngageText',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='C2GSSetEngageText.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=155,
)


_C2GSDISSOLVEENGAGE = _descriptor.Descriptor(
  name='C2GSDissolveEngage',
  full_name='C2GSDissolveEngage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=177,
)


_C2GSCANCELENGAGE = _descriptor.Descriptor(
  name='C2GSCancelEngage',
  full_name='C2GSCancelEngage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=197,
)

DESCRIPTOR.message_types_by_name['C2GSEngageCondition'] = _C2GSENGAGECONDITION
DESCRIPTOR.message_types_by_name['C2GSStartEngage'] = _C2GSSTARTENGAGE
DESCRIPTOR.message_types_by_name['C2GSConfirmEngage'] = _C2GSCONFIRMENGAGE
DESCRIPTOR.message_types_by_name['C2GSSetEngageText'] = _C2GSSETENGAGETEXT
DESCRIPTOR.message_types_by_name['C2GSDissolveEngage'] = _C2GSDISSOLVEENGAGE
DESCRIPTOR.message_types_by_name['C2GSCancelEngage'] = _C2GSCANCELENGAGE

C2GSEngageCondition = _reflection.GeneratedProtocolMessageType('C2GSEngageCondition', (_message.Message,), dict(
  DESCRIPTOR = _C2GSENGAGECONDITION,
  __module__ = 'engage_pb2'
  # @@protoc_insertion_point(class_scope:C2GSEngageCondition)
  ))
_sym_db.RegisterMessage(C2GSEngageCondition)

C2GSStartEngage = _reflection.GeneratedProtocolMessageType('C2GSStartEngage', (_message.Message,), dict(
  DESCRIPTOR = _C2GSSTARTENGAGE,
  __module__ = 'engage_pb2'
  # @@protoc_insertion_point(class_scope:C2GSStartEngage)
  ))
_sym_db.RegisterMessage(C2GSStartEngage)

C2GSConfirmEngage = _reflection.GeneratedProtocolMessageType('C2GSConfirmEngage', (_message.Message,), dict(
  DESCRIPTOR = _C2GSCONFIRMENGAGE,
  __module__ = 'engage_pb2'
  # @@protoc_insertion_point(class_scope:C2GSConfirmEngage)
  ))
_sym_db.RegisterMessage(C2GSConfirmEngage)

C2GSSetEngageText = _reflection.GeneratedProtocolMessageType('C2GSSetEngageText', (_message.Message,), dict(
  DESCRIPTOR = _C2GSSETENGAGETEXT,
  __module__ = 'engage_pb2'
  # @@protoc_insertion_point(class_scope:C2GSSetEngageText)
  ))
_sym_db.RegisterMessage(C2GSSetEngageText)

C2GSDissolveEngage = _reflection.GeneratedProtocolMessageType('C2GSDissolveEngage', (_message.Message,), dict(
  DESCRIPTOR = _C2GSDISSOLVEENGAGE,
  __module__ = 'engage_pb2'
  # @@protoc_insertion_point(class_scope:C2GSDissolveEngage)
  ))
_sym_db.RegisterMessage(C2GSDissolveEngage)

C2GSCancelEngage = _reflection.GeneratedProtocolMessageType('C2GSCancelEngage', (_message.Message,), dict(
  DESCRIPTOR = _C2GSCANCELENGAGE,
  __module__ = 'engage_pb2'
  # @@protoc_insertion_point(class_scope:C2GSCancelEngage)
  ))
_sym_db.RegisterMessage(C2GSCancelEngage)


# @@protoc_insertion_point(module_scope)
