# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kuafu.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kuafu.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0bkuafu.proto\",\n\x0e\x43\x32GSTryEnterKS\x12\n\n\x02ks\x18\x01 \x01(\t\x12\x0e\n\x06hdname\x18\x02 \x01(\t\"\x0f\n\rC2GSTryBackGS')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_C2GSTRYENTERKS = _descriptor.Descriptor(
  name='C2GSTryEnterKS',
  full_name='C2GSTryEnterKS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ks', full_name='C2GSTryEnterKS.ks', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hdname', full_name='C2GSTryEnterKS.hdname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=59,
)


_C2GSTRYBACKGS = _descriptor.Descriptor(
  name='C2GSTryBackGS',
  full_name='C2GSTryBackGS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=76,
)

DESCRIPTOR.message_types_by_name['C2GSTryEnterKS'] = _C2GSTRYENTERKS
DESCRIPTOR.message_types_by_name['C2GSTryBackGS'] = _C2GSTRYBACKGS

C2GSTryEnterKS = _reflection.GeneratedProtocolMessageType('C2GSTryEnterKS', (_message.Message,), dict(
  DESCRIPTOR = _C2GSTRYENTERKS,
  __module__ = 'kuafu_pb2'
  # @@protoc_insertion_point(class_scope:C2GSTryEnterKS)
  ))
_sym_db.RegisterMessage(C2GSTryEnterKS)

C2GSTryBackGS = _reflection.GeneratedProtocolMessageType('C2GSTryBackGS', (_message.Message,), dict(
  DESCRIPTOR = _C2GSTRYBACKGS,
  __module__ = 'kuafu_pb2'
  # @@protoc_insertion_point(class_scope:C2GSTryBackGS)
  ))
_sym_db.RegisterMessage(C2GSTryBackGS)


# @@protoc_insertion_point(module_scope)
