# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mentoring.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mentoring.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0fmentoring.proto\".\n\x07mOption\x12\x13\n\x0bquestion_id\x18\x01 \x01(\r\x12\x0e\n\x06\x61nswer\x18\x02 \x01(\r\"/\n\x0e\x43\x32GSToBeMentor\x12\x1d\n\x0boption_list\x18\x01 \x03(\x0b\x32\x08.mOption\"3\n\x12\x43\x32GSToBeApprentice\x12\x1d\n\x0boption_list\x18\x01 \x03(\x0b\x32\x08.mOption\"+\n\x1c\x43\x32GSDirectBuildReleationship\x12\x0b\n\x03pid\x18\x01 \x01(\r\"D\n\x17\x43\x32GSMentoringTaskReward\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\x0e\n\x06target\x18\x02 \x01(\r\x12\x0b\n\x03idx\x18\x03 \x01(\r\"J\n\x1d\x43\x32GSMentoringStepResultReward\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\x0e\n\x06target\x18\x02 \x01(\r\x12\x0b\n\x03idx\x18\x03 \x01(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MOPTION = _descriptor.Descriptor(
  name='mOption',
  full_name='mOption',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='question_id', full_name='mOption.question_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='answer', full_name='mOption.answer', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=65,
)


_C2GSTOBEMENTOR = _descriptor.Descriptor(
  name='C2GSToBeMentor',
  full_name='C2GSToBeMentor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='option_list', full_name='C2GSToBeMentor.option_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=114,
)


_C2GSTOBEAPPRENTICE = _descriptor.Descriptor(
  name='C2GSToBeApprentice',
  full_name='C2GSToBeApprentice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='option_list', full_name='C2GSToBeApprentice.option_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=167,
)


_C2GSDIRECTBUILDRELEATIONSHIP = _descriptor.Descriptor(
  name='C2GSDirectBuildReleationship',
  full_name='C2GSDirectBuildReleationship',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='C2GSDirectBuildReleationship.pid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=212,
)


_C2GSMENTORINGTASKREWARD = _descriptor.Descriptor(
  name='C2GSMentoringTaskReward',
  full_name='C2GSMentoringTaskReward',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='C2GSMentoringTaskReward.type', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target', full_name='C2GSMentoringTaskReward.target', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='idx', full_name='C2GSMentoringTaskReward.idx', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=282,
)


_C2GSMENTORINGSTEPRESULTREWARD = _descriptor.Descriptor(
  name='C2GSMentoringStepResultReward',
  full_name='C2GSMentoringStepResultReward',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='C2GSMentoringStepResultReward.type', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target', full_name='C2GSMentoringStepResultReward.target', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='idx', full_name='C2GSMentoringStepResultReward.idx', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=358,
)

_C2GSTOBEMENTOR.fields_by_name['option_list'].message_type = _MOPTION
_C2GSTOBEAPPRENTICE.fields_by_name['option_list'].message_type = _MOPTION
DESCRIPTOR.message_types_by_name['mOption'] = _MOPTION
DESCRIPTOR.message_types_by_name['C2GSToBeMentor'] = _C2GSTOBEMENTOR
DESCRIPTOR.message_types_by_name['C2GSToBeApprentice'] = _C2GSTOBEAPPRENTICE
DESCRIPTOR.message_types_by_name['C2GSDirectBuildReleationship'] = _C2GSDIRECTBUILDRELEATIONSHIP
DESCRIPTOR.message_types_by_name['C2GSMentoringTaskReward'] = _C2GSMENTORINGTASKREWARD
DESCRIPTOR.message_types_by_name['C2GSMentoringStepResultReward'] = _C2GSMENTORINGSTEPRESULTREWARD

mOption = _reflection.GeneratedProtocolMessageType('mOption', (_message.Message,), dict(
  DESCRIPTOR = _MOPTION,
  __module__ = 'mentoring_pb2'
  # @@protoc_insertion_point(class_scope:mOption)
  ))
_sym_db.RegisterMessage(mOption)

C2GSToBeMentor = _reflection.GeneratedProtocolMessageType('C2GSToBeMentor', (_message.Message,), dict(
  DESCRIPTOR = _C2GSTOBEMENTOR,
  __module__ = 'mentoring_pb2'
  # @@protoc_insertion_point(class_scope:C2GSToBeMentor)
  ))
_sym_db.RegisterMessage(C2GSToBeMentor)

C2GSToBeApprentice = _reflection.GeneratedProtocolMessageType('C2GSToBeApprentice', (_message.Message,), dict(
  DESCRIPTOR = _C2GSTOBEAPPRENTICE,
  __module__ = 'mentoring_pb2'
  # @@protoc_insertion_point(class_scope:C2GSToBeApprentice)
  ))
_sym_db.RegisterMessage(C2GSToBeApprentice)

C2GSDirectBuildReleationship = _reflection.GeneratedProtocolMessageType('C2GSDirectBuildReleationship', (_message.Message,), dict(
  DESCRIPTOR = _C2GSDIRECTBUILDRELEATIONSHIP,
  __module__ = 'mentoring_pb2'
  # @@protoc_insertion_point(class_scope:C2GSDirectBuildReleationship)
  ))
_sym_db.RegisterMessage(C2GSDirectBuildReleationship)

C2GSMentoringTaskReward = _reflection.GeneratedProtocolMessageType('C2GSMentoringTaskReward', (_message.Message,), dict(
  DESCRIPTOR = _C2GSMENTORINGTASKREWARD,
  __module__ = 'mentoring_pb2'
  # @@protoc_insertion_point(class_scope:C2GSMentoringTaskReward)
  ))
_sym_db.RegisterMessage(C2GSMentoringTaskReward)

C2GSMentoringStepResultReward = _reflection.GeneratedProtocolMessageType('C2GSMentoringStepResultReward', (_message.Message,), dict(
  DESCRIPTOR = _C2GSMENTORINGSTEPRESULTREWARD,
  __module__ = 'mentoring_pb2'
  # @@protoc_insertion_point(class_scope:C2GSMentoringStepResultReward)
  ))
_sym_db.RegisterMessage(C2GSMentoringStepResultReward)


# @@protoc_insertion_point(module_scope)
