# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: npc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='npc.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\tnpc.proto\"\x1d\n\x0c\x43\x32GSClickNpc\x12\r\n\x05npcid\x18\x01 \x01(\r\"/\n\x0e\x43\x32GSNpcRespond\x12\r\n\x05npcid\x18\x01 \x01(\r\x12\x0e\n\x06\x61nswer\x18\x02 \x01(\r\"$\n\x11\x43\x32GSFindPathToNpc\x12\x0f\n\x07npctype\x18\x01 \x01(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_C2GSCLICKNPC = _descriptor.Descriptor(
  name='C2GSClickNpc',
  full_name='C2GSClickNpc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='npcid', full_name='C2GSClickNpc.npcid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=42,
)


_C2GSNPCRESPOND = _descriptor.Descriptor(
  name='C2GSNpcRespond',
  full_name='C2GSNpcRespond',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='npcid', full_name='C2GSNpcRespond.npcid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='answer', full_name='C2GSNpcRespond.answer', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=91,
)


_C2GSFINDPATHTONPC = _descriptor.Descriptor(
  name='C2GSFindPathToNpc',
  full_name='C2GSFindPathToNpc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='npctype', full_name='C2GSFindPathToNpc.npctype', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=129,
)

DESCRIPTOR.message_types_by_name['C2GSClickNpc'] = _C2GSCLICKNPC
DESCRIPTOR.message_types_by_name['C2GSNpcRespond'] = _C2GSNPCRESPOND
DESCRIPTOR.message_types_by_name['C2GSFindPathToNpc'] = _C2GSFINDPATHTONPC

C2GSClickNpc = _reflection.GeneratedProtocolMessageType('C2GSClickNpc', (_message.Message,), dict(
  DESCRIPTOR = _C2GSCLICKNPC,
  __module__ = 'npc_pb2'
  # @@protoc_insertion_point(class_scope:C2GSClickNpc)
  ))
_sym_db.RegisterMessage(C2GSClickNpc)

C2GSNpcRespond = _reflection.GeneratedProtocolMessageType('C2GSNpcRespond', (_message.Message,), dict(
  DESCRIPTOR = _C2GSNPCRESPOND,
  __module__ = 'npc_pb2'
  # @@protoc_insertion_point(class_scope:C2GSNpcRespond)
  ))
_sym_db.RegisterMessage(C2GSNpcRespond)

C2GSFindPathToNpc = _reflection.GeneratedProtocolMessageType('C2GSFindPathToNpc', (_message.Message,), dict(
  DESCRIPTOR = _C2GSFINDPATHTONPC,
  __module__ = 'npc_pb2'
  # @@protoc_insertion_point(class_scope:C2GSFindPathToNpc)
  ))
_sym_db.RegisterMessage(C2GSFindPathToNpc)


# @@protoc_insertion_point(module_scope)
