# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ride.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ride.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\nride.proto\"#\n\x10\x43\x32GSActivateRide\x12\x0f\n\x07ride_id\x18\x01 \x01(\r\",\n\x0b\x43\x32GSUseRide\x12\x0f\n\x07ride_id\x18\x01 \x01(\r\x12\x0c\n\x04\x66lag\x18\x02 \x01(\r\"\x1f\n\x0f\x43\x32GSUpGradeRide\x12\x0c\n\x04\x66lag\x18\x01 \x01(\r\"%\n\x12\x43\x32GSBuyRideUseTime\x12\x0f\n\x07sell_id\x18\x01 \x01(\r\"#\n\x13\x43\x32GSRandomRideSkill\x12\x0c\n\x04\x66lag\x18\x01 \x01(\r\"\x15\n\x13\x43\x32GSShowRandomSkill\"&\n\x12\x43\x32GSLearnRideSkill\x12\x10\n\x08skill_id\x18\x01 \x01(\r\"5\n\x13\x43\x32GSForgetRideSkill\x12\x10\n\x08skill_id\x18\x01 \x01(\r\x12\x0c\n\x04\x66lag\x18\x02 \x01(\r\".\n\x0e\x43\x32GSSetRideFly\x12\x0f\n\x07ride_id\x18\x01 \x01(\r\x12\x0b\n\x03\x66ly\x18\x02 \x01(\r\"\x11\n\x0f\x43\x32GSGetRideInfo\"\x14\n\x12\x43\x32GSResetSkillInfo\"\x14\n\x12\x43\x32GSResetRideSkill\"\"\n\x12\x43\x32GSBreakRideGrade\x12\x0c\n\x04\x66lag\x18\x01 \x01(\r\">\n\x0f\x43\x32GSWieldWenShi\x12\x0e\n\x06rideid\x18\x01 \x01(\r\x12\x0e\n\x06itemid\x18\x02 \x01(\r\x12\x0b\n\x03pos\x18\x03 \x01(\r\"0\n\x11\x43\x32GSUnWieldWenShi\x12\x0e\n\x06rideid\x18\x01 \x01(\r\x12\x0b\n\x03pos\x18\x02 \x01(\r\"B\n\x11\x43\x32GSControlSummon\x12\x0e\n\x06rideid\x18\x01 \x01(\r\x12\x10\n\x08summonid\x18\x02 \x01(\r\x12\x0b\n\x03pos\x18\x03 \x01(\r\"2\n\x13\x43\x32GSUnControlSummon\x12\x0e\n\x06rideid\x18\x01 \x01(\r\x12\x0b\n\x03pos\x18\x02 \x01(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_C2GSACTIVATERIDE = _descriptor.Descriptor(
  name='C2GSActivateRide',
  full_name='C2GSActivateRide',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ride_id', full_name='C2GSActivateRide.ride_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=49,
)


_C2GSUSERIDE = _descriptor.Descriptor(
  name='C2GSUseRide',
  full_name='C2GSUseRide',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ride_id', full_name='C2GSUseRide.ride_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flag', full_name='C2GSUseRide.flag', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=95,
)


_C2GSUPGRADERIDE = _descriptor.Descriptor(
  name='C2GSUpGradeRide',
  full_name='C2GSUpGradeRide',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='flag', full_name='C2GSUpGradeRide.flag', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=128,
)


_C2GSBUYRIDEUSETIME = _descriptor.Descriptor(
  name='C2GSBuyRideUseTime',
  full_name='C2GSBuyRideUseTime',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sell_id', full_name='C2GSBuyRideUseTime.sell_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=167,
)


_C2GSRANDOMRIDESKILL = _descriptor.Descriptor(
  name='C2GSRandomRideSkill',
  full_name='C2GSRandomRideSkill',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='flag', full_name='C2GSRandomRideSkill.flag', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=204,
)


_C2GSSHOWRANDOMSKILL = _descriptor.Descriptor(
  name='C2GSShowRandomSkill',
  full_name='C2GSShowRandomSkill',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=227,
)


_C2GSLEARNRIDESKILL = _descriptor.Descriptor(
  name='C2GSLearnRideSkill',
  full_name='C2GSLearnRideSkill',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='skill_id', full_name='C2GSLearnRideSkill.skill_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=229,
  serialized_end=267,
)


_C2GSFORGETRIDESKILL = _descriptor.Descriptor(
  name='C2GSForgetRideSkill',
  full_name='C2GSForgetRideSkill',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='skill_id', full_name='C2GSForgetRideSkill.skill_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flag', full_name='C2GSForgetRideSkill.flag', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=322,
)


_C2GSSETRIDEFLY = _descriptor.Descriptor(
  name='C2GSSetRideFly',
  full_name='C2GSSetRideFly',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ride_id', full_name='C2GSSetRideFly.ride_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fly', full_name='C2GSSetRideFly.fly', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=324,
  serialized_end=370,
)


_C2GSGETRIDEINFO = _descriptor.Descriptor(
  name='C2GSGetRideInfo',
  full_name='C2GSGetRideInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=372,
  serialized_end=389,
)


_C2GSRESETSKILLINFO = _descriptor.Descriptor(
  name='C2GSResetSkillInfo',
  full_name='C2GSResetSkillInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=411,
)


_C2GSRESETRIDESKILL = _descriptor.Descriptor(
  name='C2GSResetRideSkill',
  full_name='C2GSResetRideSkill',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=413,
  serialized_end=433,
)


_C2GSBREAKRIDEGRADE = _descriptor.Descriptor(
  name='C2GSBreakRideGrade',
  full_name='C2GSBreakRideGrade',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='flag', full_name='C2GSBreakRideGrade.flag', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=435,
  serialized_end=469,
)


_C2GSWIELDWENSHI = _descriptor.Descriptor(
  name='C2GSWieldWenShi',
  full_name='C2GSWieldWenShi',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rideid', full_name='C2GSWieldWenShi.rideid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='itemid', full_name='C2GSWieldWenShi.itemid', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pos', full_name='C2GSWieldWenShi.pos', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=471,
  serialized_end=533,
)


_C2GSUNWIELDWENSHI = _descriptor.Descriptor(
  name='C2GSUnWieldWenShi',
  full_name='C2GSUnWieldWenShi',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rideid', full_name='C2GSUnWieldWenShi.rideid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pos', full_name='C2GSUnWieldWenShi.pos', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=535,
  serialized_end=583,
)


_C2GSCONTROLSUMMON = _descriptor.Descriptor(
  name='C2GSControlSummon',
  full_name='C2GSControlSummon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rideid', full_name='C2GSControlSummon.rideid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='summonid', full_name='C2GSControlSummon.summonid', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pos', full_name='C2GSControlSummon.pos', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=585,
  serialized_end=651,
)


_C2GSUNCONTROLSUMMON = _descriptor.Descriptor(
  name='C2GSUnControlSummon',
  full_name='C2GSUnControlSummon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rideid', full_name='C2GSUnControlSummon.rideid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pos', full_name='C2GSUnControlSummon.pos', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=653,
  serialized_end=703,
)

DESCRIPTOR.message_types_by_name['C2GSActivateRide'] = _C2GSACTIVATERIDE
DESCRIPTOR.message_types_by_name['C2GSUseRide'] = _C2GSUSERIDE
DESCRIPTOR.message_types_by_name['C2GSUpGradeRide'] = _C2GSUPGRADERIDE
DESCRIPTOR.message_types_by_name['C2GSBuyRideUseTime'] = _C2GSBUYRIDEUSETIME
DESCRIPTOR.message_types_by_name['C2GSRandomRideSkill'] = _C2GSRANDOMRIDESKILL
DESCRIPTOR.message_types_by_name['C2GSShowRandomSkill'] = _C2GSSHOWRANDOMSKILL
DESCRIPTOR.message_types_by_name['C2GSLearnRideSkill'] = _C2GSLEARNRIDESKILL
DESCRIPTOR.message_types_by_name['C2GSForgetRideSkill'] = _C2GSFORGETRIDESKILL
DESCRIPTOR.message_types_by_name['C2GSSetRideFly'] = _C2GSSETRIDEFLY
DESCRIPTOR.message_types_by_name['C2GSGetRideInfo'] = _C2GSGETRIDEINFO
DESCRIPTOR.message_types_by_name['C2GSResetSkillInfo'] = _C2GSRESETSKILLINFO
DESCRIPTOR.message_types_by_name['C2GSResetRideSkill'] = _C2GSRESETRIDESKILL
DESCRIPTOR.message_types_by_name['C2GSBreakRideGrade'] = _C2GSBREAKRIDEGRADE
DESCRIPTOR.message_types_by_name['C2GSWieldWenShi'] = _C2GSWIELDWENSHI
DESCRIPTOR.message_types_by_name['C2GSUnWieldWenShi'] = _C2GSUNWIELDWENSHI
DESCRIPTOR.message_types_by_name['C2GSControlSummon'] = _C2GSCONTROLSUMMON
DESCRIPTOR.message_types_by_name['C2GSUnControlSummon'] = _C2GSUNCONTROLSUMMON

C2GSActivateRide = _reflection.GeneratedProtocolMessageType('C2GSActivateRide', (_message.Message,), dict(
  DESCRIPTOR = _C2GSACTIVATERIDE,
  __module__ = 'ride_pb2'
  # @@protoc_insertion_point(class_scope:C2GSActivateRide)
  ))
_sym_db.RegisterMessage(C2GSActivateRide)

C2GSUseRide = _reflection.GeneratedProtocolMessageType('C2GSUseRide', (_message.Message,), dict(
  DESCRIPTOR = _C2GSUSERIDE,
  __module__ = 'ride_pb2'
  # @@protoc_insertion_point(class_scope:C2GSUseRide)
  ))
_sym_db.RegisterMessage(C2GSUseRide)

C2GSUpGradeRide = _reflection.GeneratedProtocolMessageType('C2GSUpGradeRide', (_message.Message,), dict(
  DESCRIPTOR = _C2GSUPGRADERIDE,
  __module__ = 'ride_pb2'
  # @@protoc_insertion_point(class_scope:C2GSUpGradeRide)
  ))
_sym_db.RegisterMessage(C2GSUpGradeRide)

C2GSBuyRideUseTime = _reflection.GeneratedProtocolMessageType('C2GSBuyRideUseTime', (_message.Message,), dict(
  DESCRIPTOR = _C2GSBUYRIDEUSETIME,
  __module__ = 'ride_pb2'
  # @@protoc_insertion_point(class_scope:C2GSBuyRideUseTime)
  ))
_sym_db.RegisterMessage(C2GSBuyRideUseTime)

C2GSRandomRideSkill = _reflection.GeneratedProtocolMessageType('C2GSRandomRideSkill', (_message.Message,), dict(
  DESCRIPTOR = _C2GSRANDOMRIDESKILL,
  __module__ = 'ride_pb2'
  # @@protoc_insertion_point(class_scope:C2GSRandomRideSkill)
  ))
_sym_db.RegisterMessage(C2GSRandomRideSkill)

C2GSShowRandomSkill = _reflection.GeneratedProtocolMessageType('C2GSShowRandomSkill', (_message.Message,), dict(
  DESCRIPTOR = _C2GSSHOWRANDOMSKILL,
  __module__ = 'ride_pb2'
  # @@protoc_insertion_point(class_scope:C2GSShowRandomSkill)
  ))
_sym_db.RegisterMessage(C2GSShowRandomSkill)

C2GSLearnRideSkill = _reflection.GeneratedProtocolMessageType('C2GSLearnRideSkill', (_message.Message,), dict(
  DESCRIPTOR = _C2GSLEARNRIDESKILL,
  __module__ = 'ride_pb2'
  # @@protoc_insertion_point(class_scope:C2GSLearnRideSkill)
  ))
_sym_db.RegisterMessage(C2GSLearnRideSkill)

C2GSForgetRideSkill = _reflection.GeneratedProtocolMessageType('C2GSForgetRideSkill', (_message.Message,), dict(
  DESCRIPTOR = _C2GSFORGETRIDESKILL,
  __module__ = 'ride_pb2'
  # @@protoc_insertion_point(class_scope:C2GSForgetRideSkill)
  ))
_sym_db.RegisterMessage(C2GSForgetRideSkill)

C2GSSetRideFly = _reflection.GeneratedProtocolMessageType('C2GSSetRideFly', (_message.Message,), dict(
  DESCRIPTOR = _C2GSSETRIDEFLY,
  __module__ = 'ride_pb2'
  # @@protoc_insertion_point(class_scope:C2GSSetRideFly)
  ))
_sym_db.RegisterMessage(C2GSSetRideFly)

C2GSGetRideInfo = _reflection.GeneratedProtocolMessageType('C2GSGetRideInfo', (_message.Message,), dict(
  DESCRIPTOR = _C2GSGETRIDEINFO,
  __module__ = 'ride_pb2'
  # @@protoc_insertion_point(class_scope:C2GSGetRideInfo)
  ))
_sym_db.RegisterMessage(C2GSGetRideInfo)

C2GSResetSkillInfo = _reflection.GeneratedProtocolMessageType('C2GSResetSkillInfo', (_message.Message,), dict(
  DESCRIPTOR = _C2GSRESETSKILLINFO,
  __module__ = 'ride_pb2'
  # @@protoc_insertion_point(class_scope:C2GSResetSkillInfo)
  ))
_sym_db.RegisterMessage(C2GSResetSkillInfo)

C2GSResetRideSkill = _reflection.GeneratedProtocolMessageType('C2GSResetRideSkill', (_message.Message,), dict(
  DESCRIPTOR = _C2GSRESETRIDESKILL,
  __module__ = 'ride_pb2'
  # @@protoc_insertion_point(class_scope:C2GSResetRideSkill)
  ))
_sym_db.RegisterMessage(C2GSResetRideSkill)

C2GSBreakRideGrade = _reflection.GeneratedProtocolMessageType('C2GSBreakRideGrade', (_message.Message,), dict(
  DESCRIPTOR = _C2GSBREAKRIDEGRADE,
  __module__ = 'ride_pb2'
  # @@protoc_insertion_point(class_scope:C2GSBreakRideGrade)
  ))
_sym_db.RegisterMessage(C2GSBreakRideGrade)

C2GSWieldWenShi = _reflection.GeneratedProtocolMessageType('C2GSWieldWenShi', (_message.Message,), dict(
  DESCRIPTOR = _C2GSWIELDWENSHI,
  __module__ = 'ride_pb2'
  # @@protoc_insertion_point(class_scope:C2GSWieldWenShi)
  ))
_sym_db.RegisterMessage(C2GSWieldWenShi)

C2GSUnWieldWenShi = _reflection.GeneratedProtocolMessageType('C2GSUnWieldWenShi', (_message.Message,), dict(
  DESCRIPTOR = _C2GSUNWIELDWENSHI,
  __module__ = 'ride_pb2'
  # @@protoc_insertion_point(class_scope:C2GSUnWieldWenShi)
  ))
_sym_db.RegisterMessage(C2GSUnWieldWenShi)

C2GSControlSummon = _reflection.GeneratedProtocolMessageType('C2GSControlSummon', (_message.Message,), dict(
  DESCRIPTOR = _C2GSCONTROLSUMMON,
  __module__ = 'ride_pb2'
  # @@protoc_insertion_point(class_scope:C2GSControlSummon)
  ))
_sym_db.RegisterMessage(C2GSControlSummon)

C2GSUnControlSummon = _reflection.GeneratedProtocolMessageType('C2GSUnControlSummon', (_message.Message,), dict(
  DESCRIPTOR = _C2GSUNCONTROLSUMMON,
  __module__ = 'ride_pb2'
  # @@protoc_insertion_point(class_scope:C2GSUnControlSummon)
  ))
_sym_db.RegisterMessage(C2GSUnControlSummon)


# @@protoc_insertion_point(module_scope)
