# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tempitem.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tempitem.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0etempitem.proto\"\x1f\n\x11\x43\x32GSTranToItemBag\x12\n\n\x02id\x18\x01 \x01(\r\"\x14\n\x12\x43\x32GSOpenTempItemUI')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_C2GSTRANTOITEMBAG = _descriptor.Descriptor(
  name='C2GSTranToItemBag',
  full_name='C2GSTranToItemBag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='C2GSTranToItemBag.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=49,
)


_C2GSOPENTEMPITEMUI = _descriptor.Descriptor(
  name='C2GSOpenTempItemUI',
  full_name='C2GSOpenTempItemUI',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=71,
)

DESCRIPTOR.message_types_by_name['C2GSTranToItemBag'] = _C2GSTRANTOITEMBAG
DESCRIPTOR.message_types_by_name['C2GSOpenTempItemUI'] = _C2GSOPENTEMPITEMUI

C2GSTranToItemBag = _reflection.GeneratedProtocolMessageType('C2GSTranToItemBag', (_message.Message,), dict(
  DESCRIPTOR = _C2GSTRANTOITEMBAG,
  __module__ = 'tempitem_pb2'
  # @@protoc_insertion_point(class_scope:C2GSTranToItemBag)
  ))
_sym_db.RegisterMessage(C2GSTranToItemBag)

C2GSOpenTempItemUI = _reflection.GeneratedProtocolMessageType('C2GSOpenTempItemUI', (_message.Message,), dict(
  DESCRIPTOR = _C2GSOPENTEMPITEMUI,
  __module__ = 'tempitem_pb2'
  # @@protoc_insertion_point(class_scope:C2GSOpenTempItemUI)
  ))
_sym_db.RegisterMessage(C2GSOpenTempItemUI)


# @@protoc_insertion_point(module_scope)
