# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: title.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='title.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0btitle.proto\")\n\x0c\x43\x32GSUseTitle\x12\x0b\n\x03tid\x18\x01 \x01(\r\x12\x0c\n\x04\x66lag\x18\x02 \x01(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_C2GSUSETITLE = _descriptor.Descriptor(
  name='C2GSUseTitle',
  full_name='C2GSUseTitle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tid', full_name='C2GSUseTitle.tid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flag', full_name='C2GSUseTitle.flag', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=56,
)

DESCRIPTOR.message_types_by_name['C2GSUseTitle'] = _C2GSUSETITLE

C2GSUseTitle = _reflection.GeneratedProtocolMessageType('C2GSUseTitle', (_message.Message,), dict(
  DESCRIPTOR = _C2GSUSETITLE,
  __module__ = 'title_pb2'
  # @@protoc_insertion_point(class_scope:C2GSUseTitle)
  ))
_sym_db.RegisterMessage(C2GSUseTitle)


# @@protoc_insertion_point(module_scope)
