# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: warehouse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='warehouse.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0fwarehouse.proto\"\"\n\x13\x43\x32GSSwitchWareHouse\x12\x0b\n\x03wid\x18\x01 \x01(\r\"\x12\n\x10\x43\x32GSBuyWareHouse\"0\n\x13\x43\x32GSRenameWareHouse\x12\x0b\n\x03wid\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\"5\n\x16\x43\x32GSWareHouseWithStore\x12\x0b\n\x03wid\x18\x01 \x01(\r\x12\x0e\n\x06itemid\x18\x02 \x01(\r\"1\n\x15\x43\x32GSWareHouseWithDraw\x12\x0b\n\x03wid\x18\x01 \x01(\r\x12\x0b\n\x03pos\x18\x02 \x01(\r\"#\n\x14\x43\x32GSWareHouseArrange\x12\x0b\n\x03wid\x18\x01 \x01(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_C2GSSWITCHWAREHOUSE = _descriptor.Descriptor(
  name='C2GSSwitchWareHouse',
  full_name='C2GSSwitchWareHouse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wid', full_name='C2GSSwitchWareHouse.wid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=53,
)


_C2GSBUYWAREHOUSE = _descriptor.Descriptor(
  name='C2GSBuyWareHouse',
  full_name='C2GSBuyWareHouse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=73,
)


_C2GSRENAMEWAREHOUSE = _descriptor.Descriptor(
  name='C2GSRenameWareHouse',
  full_name='C2GSRenameWareHouse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wid', full_name='C2GSRenameWareHouse.wid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='C2GSRenameWareHouse.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=123,
)


_C2GSWAREHOUSEWITHSTORE = _descriptor.Descriptor(
  name='C2GSWareHouseWithStore',
  full_name='C2GSWareHouseWithStore',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wid', full_name='C2GSWareHouseWithStore.wid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='itemid', full_name='C2GSWareHouseWithStore.itemid', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=178,
)


_C2GSWAREHOUSEWITHDRAW = _descriptor.Descriptor(
  name='C2GSWareHouseWithDraw',
  full_name='C2GSWareHouseWithDraw',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wid', full_name='C2GSWareHouseWithDraw.wid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pos', full_name='C2GSWareHouseWithDraw.pos', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=229,
)


_C2GSWAREHOUSEARRANGE = _descriptor.Descriptor(
  name='C2GSWareHouseArrange',
  full_name='C2GSWareHouseArrange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wid', full_name='C2GSWareHouseArrange.wid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=266,
)

DESCRIPTOR.message_types_by_name['C2GSSwitchWareHouse'] = _C2GSSWITCHWAREHOUSE
DESCRIPTOR.message_types_by_name['C2GSBuyWareHouse'] = _C2GSBUYWAREHOUSE
DESCRIPTOR.message_types_by_name['C2GSRenameWareHouse'] = _C2GSRENAMEWAREHOUSE
DESCRIPTOR.message_types_by_name['C2GSWareHouseWithStore'] = _C2GSWAREHOUSEWITHSTORE
DESCRIPTOR.message_types_by_name['C2GSWareHouseWithDraw'] = _C2GSWAREHOUSEWITHDRAW
DESCRIPTOR.message_types_by_name['C2GSWareHouseArrange'] = _C2GSWAREHOUSEARRANGE

C2GSSwitchWareHouse = _reflection.GeneratedProtocolMessageType('C2GSSwitchWareHouse', (_message.Message,), dict(
  DESCRIPTOR = _C2GSSWITCHWAREHOUSE,
  __module__ = 'warehouse_pb2'
  # @@protoc_insertion_point(class_scope:C2GSSwitchWareHouse)
  ))
_sym_db.RegisterMessage(C2GSSwitchWareHouse)

C2GSBuyWareHouse = _reflection.GeneratedProtocolMessageType('C2GSBuyWareHouse', (_message.Message,), dict(
  DESCRIPTOR = _C2GSBUYWAREHOUSE,
  __module__ = 'warehouse_pb2'
  # @@protoc_insertion_point(class_scope:C2GSBuyWareHouse)
  ))
_sym_db.RegisterMessage(C2GSBuyWareHouse)

C2GSRenameWareHouse = _reflection.GeneratedProtocolMessageType('C2GSRenameWareHouse', (_message.Message,), dict(
  DESCRIPTOR = _C2GSRENAMEWAREHOUSE,
  __module__ = 'warehouse_pb2'
  # @@protoc_insertion_point(class_scope:C2GSRenameWareHouse)
  ))
_sym_db.RegisterMessage(C2GSRenameWareHouse)

C2GSWareHouseWithStore = _reflection.GeneratedProtocolMessageType('C2GSWareHouseWithStore', (_message.Message,), dict(
  DESCRIPTOR = _C2GSWAREHOUSEWITHSTORE,
  __module__ = 'warehouse_pb2'
  # @@protoc_insertion_point(class_scope:C2GSWareHouseWithStore)
  ))
_sym_db.RegisterMessage(C2GSWareHouseWithStore)

C2GSWareHouseWithDraw = _reflection.GeneratedProtocolMessageType('C2GSWareHouseWithDraw', (_message.Message,), dict(
  DESCRIPTOR = _C2GSWAREHOUSEWITHDRAW,
  __module__ = 'warehouse_pb2'
  # @@protoc_insertion_point(class_scope:C2GSWareHouseWithDraw)
  ))
_sym_db.RegisterMessage(C2GSWareHouseWithDraw)

C2GSWareHouseArrange = _reflection.GeneratedProtocolMessageType('C2GSWareHouseArrange', (_message.Message,), dict(
  DESCRIPTOR = _C2GSWAREHOUSEARRANGE,
  __module__ = 'warehouse_pb2'
  # @@protoc_insertion_point(class_scope:C2GSWareHouseArrange)
  ))
_sym_db.RegisterMessage(C2GSWareHouseArrange)


# @@protoc_insertion_point(module_scope)
